USE master
IF NOT EXISTS (SELECT NULL FROM [sys].[server_principals] WHERE [name]='{Login}')
	CREATE LOGIN [{Login}] WITH PASSWORD=N'{Password}',CHECK_POLICY=ON,CHECK_EXPIRATION=ON
ELSE
	ALTER LOGIN [{Login}] WITH PASSWORD=N'{Password}',CHECK_POLICY=ON,CHECK_EXPIRATION=ON
