// ATL_NetLib.idl : IDL source for ATL_NetLib.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (ATL_NetLib.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

interface IConfig;
interface IUser;
interface IUsers;
interface IPromo;
interface IPromos;
interface IMessage;
interface IMessages;
interface IlocalSID;
interface IlocalSIDs;
interface IFile;
interface IFiles;
interface IChat;
interface IChats;
	
	
	[
		object,
		uuid(AEB8A2D7-1854-42A6-9F19-592DB16930DA),
		dual,
		helpstring("ISession Interface"),
		pointer_default(unique)
	]
	interface ISession : IDispatch
	{
		[propget, id(1), helpstring("property SID")] HRESULT SID([out, retval] BSTR *pVal);
		[propget, id(2), helpstring("property SelfInfo")] HRESULT SelfInfo([out, retval] IUser** pVal);
		[propget, id(3), helpstring("property Config")] HRESULT Config([out, retval] IConfig** pVal);
		
		[id(4), helpstring("method LogOn")] HRESULT LogOn(BSTR UserName, BSTR Password, long Status, [out, retval] long* Handle);
		[id(5), helpstring("method ChangeStatus")] HRESULT ChangeStatus(long Status);
		[id(6), helpstring("method LogOff")] HRESULT LogOff();

		[id(7), helpstring("method CreateMessage")] HRESULT CreateMessage([out, retval] IMessage **ppMessage);
		[id(8), helpstring("method CreateFile")] HRESULT CreateFile([out, retval] IFile** ppFile);
		[id(9), helpstring("method CreatePromo")] HRESULT CreatePromo([out, retval] IPromo** ppPromo);
		
		[id(10), helpstring("method AddUser")] HRESULT AddUser([in]long User_ID, [in] BSTR Body,[in]long ListType, [out, retval] long* Handle);
		[id(11), helpstring("method DeleteUser")] HRESULT DeleteUser([in] long User_ID, [in] long ListType, [out, retval] long* Handle);
		[id(12), helpstring("method LoadSIDs")] HRESULT LoadSIDs([in] long From, [in] long To, [out, retval] long* Handle);
		[id(13), helpstring("method LoadMessages")] HRESULT LoadMessages([in] BSTR SID, [out,retval] long* Handle);
		[id(14), helpstring("method LoadIgnore")] HRESULT LoadIgnore([out, retval] long* Handle);
		[id(15), helpstring("method LoadOffLineFiles")] HRESULT LoadOffLineFiles([out, retval] long* Handle);
		[id(16), helpstring("method AddUserReply")] HRESULT AddUserReply([in] long User_ID, [in] long Result, [out,retval] long* Handle);
		[id(17), helpstring("method ConfirmFile")] HRESULT ConfirmFile([in] BSTR FID, [in] long Result, [out,retval] long* Handle);
		[id(18), helpstring("method UserDetails")] HRESULT UserDetails([in] long User_ID, [in] long InfoType, [out,retval] long* Handle);
		[id(19), helpstring("method GetLastPromos")] HRESULT GetLastPromos([in] long Count, [out,retval] long* Handle);
		[id(20), helpstring("method CancelOperation")] HRESULT CancelOperation([in] long Handle);
		[id(21), helpstring("method DeleteUserR")] HRESULT DeleteUserR([in] long User_ID, [out,retval] long * Handle);
		[id(22), helpstring("method CreateChat")] HRESULT CreateChat([in] BSTR CID, [in] BSTR bsName, [in] BSTR Descr, [out,retval] long* Handle);
	};

[
	uuid(EB37EA05-FBA5-4F43-92B3-E485128055CB),
	version(1.0),
	helpstring("Mediachase IM NetLib 1.0 Type Library")
]
library ATL_NETLIBLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	
	typedef enum {Monday=2, Tuesday, Wednesday, Thursday, Friday} workdays; 

	[
		object,
		uuid(EB3309A2-7275-46C6-AE91-DD3E21C2DAD3),
		dual,
		helpstring("IUser Interface"),
		pointer_default(unique)
	]
	interface IUser : IDispatch
	{
/*		[propget, id(1), helpstring("property UserName")] HRESULT UserName([out, retval] BSTR *pVal);
		[propput, id(1), helpstring("property UserName")] HRESULT UserName([in] BSTR newVal);
		[propget, id(2), helpstring("property FirstName")] HRESULT FirstName([out, retval] BSTR *pVal);
		[propput, id(2), helpstring("property FirstName")] HRESULT FirstName([in] BSTR newVal);
		[propget, id(3), helpstring("property LastName")] HRESULT LastName([out, retval] BSTR *pVal);
		[propput, id(3), helpstring("property LastName")] HRESULT LastName([in] BSTR newVal);
		[propget, id(4), helpstring("property EMail")] HRESULT EMail([out, retval] BSTR *pVal);
		[propput, id(4), helpstring("property EMail")] HRESULT EMail([in] BSTR newVal);
		[propget, id(5), helpstring("property Status")] HRESULT Status([out, retval] long *pVal);
		[propput, id(5), helpstring("property Status")] HRESULT Status([in] long newVal);
		[propget, id(6), helpstring("property ID")] HRESULT ID([out, retval] long *pVal);
		[propput, id(6), helpstring("property ID")] HRESULT ID([in] long newVal);
		[propget, id(7), helpstring("property CompanyName")] HRESULT CompanyName([out, retval] BSTR *pVal);
		[propput, id(7), helpstring("property CompanyName")] HRESULT CompanyName([in] BSTR newVal);
		[propget, id(8), helpstring("property Company_ID")] HRESULT Company_ID([out, retval] long *pVal);
		[propput, id(8), helpstring("property Company_ID")] HRESULT Company_ID([in] long newVal);
		[propget, id(9), helpstring("property Role")] HRESULT Role([out, retval] BSTR *pVal);
		[propput, id(9), helpstring("property Role")] HRESULT Role([in] BSTR newVal);
		[propget, id(10), helpstring("property Role_ID")] HRESULT Role_ID([out, retval] long *pVal);
		[propput, id(10), helpstring("property Role_ID")] HRESULT Role_ID([in] long newVal);*/
		[propget, id(DISPID_VALUE), helpstring("property Value")] HRESULT Value([in] BSTR bsName, [out, retval] VARIANT *pVal);
		[propput, id(DISPID_VALUE), helpstring("property Value")] HRESULT Value([in] BSTR bsName, [in] VARIANT newVal);
	};

	[
		uuid(708324C5-13D3-44CC-A0AD-7FB16F450DF4),
		helpstring("_ISessionEvents Interface")
	]
	dispinterface _ISessionEvents
	{
		properties:
		methods:
		[id(1), helpstring("method ChangedState")]	HRESULT ChangedState([in]long State,[in] long ErrorType,[in] long ErrorCode);
		
		[id(2), helpstring("method eChangedStatus")]HRESULT eChangedStatus([in]IUser* pUser);
		[id(3), helpstring("method eMessage")]		HRESULT eMessage([in] IMessage* pMessage);
		[id(4), helpstring("method ePromo")]		HRESULT ePromo([in] IPromo* pPromo, [in] BSTR PromoAsString);
		[id(5), helpstring("method eFile")]			HRESULT eFile([in] IFile* pFile);
		[id(6), helpstring("method eAdd")]			HRESULT eAdd([in] IUser* pUser, [in] BSTR bstrMessage);
		[id(7), helpstring("method eAddR")]			HRESULT eAddR([in] IUser* User, [in] long nResult);
		[id(8), helpstring("method eReklama")]		HRESULT eReklama([in] BSTR bstrURL);
		
		[id(9),  helpstring("method ContactList")]	HRESULT ContactList([in] IUsers* pUsers);
		[id(10), helpstring("method IgnoreList")]	HRESULT IgnoreList([in] long Handle, [in] IUsers* pUsers);
		[id(11), helpstring("method Details")]		HRESULT Details([in] long Handle, [in] IUser* pUser, [in] long type);
		[id(12), helpstring("method CommandOK")]	HRESULT CommandOK([in] long Handle, [in] long AddVal);
		[id(13), helpstring("method CommandError")]	HRESULT CommandError([in] long Handle, [in] long ErrorType, [in] long ErrorCode);

		[id(14), helpstring("method SessionsList")]	HRESULT SessionsList([in] long Handle, [in] IlocalSIDs* plocalSIDs);
		[id(15), helpstring("method OffLineFiles")]	HRESULT OffLineFiles([in] long Handle, [in] IFiles* pFiles);
		[id(16), helpstring("method MessagesList")]	HRESULT MessagesList([in] long Handle, [in] IMessages* pMessages);
		[id(17), helpstring("method PromosList")]	HRESULT PromosList([in] long Handle, [in] IPromos* pPromos, [in] BSTR PromosAsString);
		[id(18), helpstring("method SelfStatus")]	HRESULT SelfStatus([in] long Status);
		[id(19), helpstring("method eSysMess")] HRESULT eSysMess([in] LONG Code, [in] BSTR Description);
		[id(20), helpstring("method ChatList")] HRESULT ChatList([in] IChats* pChats);
		[id(21), helpstring("method ChatStatus")] HRESULT ChatStatus([in] long Handle, [in] IUsers* pUsers, [in] BSTR bsLog);
		[id(22), helpstring("method ChatCreate")] HRESULT ChatCreate([in] long Handle, [in] IChat* pChat);
		[id(23), helpstring("method eChatUserStatus")] HRESULT eChatUserStatus([in] IUser* pUser, [in] IChat* pChat);
		[id(24), helpstring("method eChatInvite")] HRESULT eChatInvite([in] IChat* pChat, [in] IUser* pUser, [in] IUser* pInvitedFriend, [in] BSTR Invitation);
		[id(25), helpstring("method eChatLeave")] HRESULT eChatLeave([in] IUser* pUser, [in] IChat* pChat);
		[id(26), helpstring("method eChatMessage")] HRESULT eChatMessage([in] IChat* pChat, [in] IMessage* pMessage);
		[id(27), helpstring("method eChatFile")] HRESULT eChatFile([in] IChat* pChat);
		[id(28), helpstring("method eChatInvite")] HRESULT eChatAccept([in] IChat* pChat, [in] IUser* pUser, [in] long result);

	};

		
	[
		object,
		uuid(6D9B52D2-0A41-450F-9D16-B1E336F9947B),
		dual,
		helpstring("IUsers Interface"),
		pointer_default(unique),
		nonextensible
	]
	interface IUsers : IDispatch
	{
		[id(1), helpstring("method AddUser")] HRESULT AddUser([out, retval] IUser** ppUser);

        [propget] HRESULT Count([out, retval] long* pnCount);

        [id(DISPID_VALUE), propget] HRESULT Item([in] long n, [out, retval] IUser** ppUser);
        
        [id(DISPID_NEWENUM), propget] HRESULT _NewEnum([out, retval] IUnknown** ppEnum);

	};
	
/*	[
		object,
		uuid(DA4E0291-FF71-4079-A0A2-0FEDDE2FCC30),
		dual,
		helpstring("ICallBackEvents Interface"),
		pointer_default(unique)
	]
	interface ICallBackEvents : IDispatch
	{
		[id(1), helpstring("method Ev_LogOn")] HRESULT Ev_LogOn(BSTR Login, long Status);
		[id(2), helpstring("method Ev_ChangesState")] HRESULT Ev_ChangesState([in] long State, [in] long ErrorType, [in] long ErrorCode);
		[id(3), helpstring("method Ev_CommandConfirm")] HRESULT Ev_CommandConfirm([in] long handle, [in] long CommandType, [in] long ErrorType, [in] long ErrorCode);
		[id(4), helpstring("method Ev_ContactList")] HRESULT Ev_ContactList([in] IUsers* pUser, [in] long type);
		[id(5), helpstring("method Ev_eMessage")] HRESULT Ev_eMessage([in] IMessage* pMessage);
		[id(6), helpstring("method Ev_eChangedStatus")] HRESULT Ev_eChangedStatus([in]IUser* pUser);
		[id(7), helpstring("method Ev_ePromo")] HRESULT Ev_ePromo([in] IPromo* pPromo);
		[id(8), helpstring("method Ev_eFile")] HRESULT Ev_eFile([in] IFile* pFile);
		[id(9), helpstring("method Ev_eReklama")] HRESULT Ev_eReklama([in] BSTR pURL);
		[id(10), helpstring("method Ev_eAddUser")] HRESULT Ev_eAddUser([in] IUser* pUser, [in] BSTR body);
		[id(11), helpstring("method Ev_eAddUserR")] HRESULT Ev_eAddUserR([in] IUser* pUser, [in] long Result);
		[id(12), helpstring("method Ev_CommandOK")] HRESULT Ev_CommandOK([in] long Handle, [in] long AddParam);
		[id(13), helpstring("method Ev_CommandError")] HRESULT Ev_CommandError([in] long Handle, [in] long ErrorType, [in] long ErrorCode);
		[id(14), helpstring("method M_ANSWER_BUFF")] HRESULT M_ANSWER_BUFF([in] long wParama, [in] long lParam);
		[id(15), helpstring("method M_NEW_EVENT")] HRESULT M_NEW_EVENT([in] long wParam, [in] long lParam);
		[id(16), helpstring("method M_CHANGE_STATE")] HRESULT M_CHANGE_STATE([in] long wParam, [in] long lParam);
		[id(17), helpstring("method M_ANSWER_OK")] HRESULT M_ANSWER_OK(long wParam, long lParam);
	};*/
	[
		object,
		uuid(7BEB6353-1BEC-4689-AC5F-52CE6F0CE0FA),
		dual,
		helpstring("IPromo Interface"),
		pointer_default(unique)
	]
	interface IPromo : IDispatch
	{
		[id(1), helpstring("method Send")] HRESULT Send([out, retval] long* Handle);
		[propget, id(2), helpstring("property PID")] HRESULT PID([out, retval] BSTR *pVal);
		[propput, id(2), helpstring("property PID")] HRESULT PID([in] BSTR newVal);
		[propget, id(3), helpstring("property date_time")] HRESULT date_time([out, retval] long *pVal);
		[propget, id(4), helpstring("property SID")] HRESULT SID([out, retval] BSTR *pVal);
		[propget, id(5), helpstring("property Subject")] HRESULT Subject([out, retval] BSTR *pVal);
		[propput, id(5), helpstring("property Subject")] HRESULT Subject([in] BSTR newVal);
		[propget, id(6), helpstring("property Product_ID")] HRESULT Product_ID([out, retval] long *pVal);
		[propput, id(6), helpstring("property Product_ID")] HRESULT Product_ID([in] long newVal);
		[propget, id(7), helpstring("property Body")] HRESULT Body([out, retval] BSTR *pVal);
		[propput, id(7), helpstring("property Body")] HRESULT Body([in] BSTR newVal);
		[propget, id(8), helpstring("property Recipients")] HRESULT Recipients([out, retval] IUsers* *pVal);
		[propget, id(9), helpstring("property Sender")] HRESULT Sender([out, retval] IUser* *pVal);
		[propget, id(10), helpstring("property ProductName")] HRESULT ProductName([out, retval] BSTR *pVal);
		[propput, id(10), helpstring("property ProductName")] HRESULT ProductName([in] BSTR newVal);

	};
	[
		object,
		uuid(459CF8BC-BB71-4DD3-B98F-2B6F65375669),
		dual,
		helpstring("IMessage Interface"),
		pointer_default(unique)
	]
	interface IMessage : IDispatch
	{
		[propget, id(1), helpstring("property Body")] HRESULT Body([out, retval] BSTR *pVal);
		[propput, id(1), helpstring("property Body")] HRESULT Body([in] BSTR newVal);
		[propget, id(2), helpstring("property date_time")] HRESULT date_time([out, retval] long *pVal);
		[propget, id(3), helpstring("property Sender")] HRESULT Sender([out, retval] IUser* *pVal);
		[propget, id(4), helpstring("property Recipients")] HRESULT Recipients([out, retval] IUsers* *pVal);
		[propget, id(5), helpstring("property MID")] HRESULT MID([out, retval] BSTR *pVal);
		[propput, id(5), helpstring("property MID")] HRESULT MID([in] BSTR newVal);
		[propget, id(6), helpstring("property SID")] HRESULT SID([out, retval] BSTR *pVal);
		[id(7), helpstring("method Send")] HRESULT Send([out] long* Handle);
		[propget, id(8), helpstring("property ID")] HRESULT ID([out, retval] long *pVal);
		
	};
	[
		object,
		uuid(48805461-FBEB-4F31-B341-4BED2C7A79AC),
		dual,
		helpstring("IFile Interface"),
		pointer_default(unique)
	]
	interface IFile : IDispatch
	{
		[propget, id(1), helpstring("property FID")] HRESULT FID([out, retval] BSTR *pVal);
		[propput, id(1), helpstring("property FID")] HRESULT FID([in] BSTR newVal);
		[propget, id(2), helpstring("property RealName")] HRESULT RealName([out, retval] BSTR *pVal);
		[propput, id(2), helpstring("property RealName")] HRESULT RealName([in] BSTR newVal);
		[propget, id(3), helpstring("property Body")] HRESULT Body([out, retval] BSTR *pVal);
		[propput, id(3), helpstring("property Body")] HRESULT Body([in] BSTR newVal);
		[propget, id(4), helpstring("property date_time")] HRESULT date_time([out, retval] long *pVal);
		[propget, id(5), helpstring("property Sender")] HRESULT Sender([out, retval] IUser* *pVal);
		[propget, id(6), helpstring("property Recipients")] HRESULT Recipients([out, retval] IUsers* *pVal);
		[propget, id(7), helpstring("property SID")] HRESULT SID([out, retval] BSTR *pVal);
		[id(8), helpstring("method Send")] HRESULT Send([out] long* Handle);
		[id(9), helpstring("method Receive")] HRESULT Receive([out] long* Handle);
		[propput, id(10), helpstring("property hWnd")] HRESULT hWnd([in] long newVal);
		[propget, id(11), helpstring("property Size")] HRESULT Size([out, retval] long *pVal);
	};
	
	
	[
		object,
		uuid(1BA9F720-B0AB-4237-BE06-DE2F55E8731C),
		helpstring("IMonitor Interface"),
		dual,
		pointer_default(unique)
	]
	interface IMonitor : IDispatch
	{

	/*
		get_MessageSent(OUT Long *plCount)
		get_MessageReceived(OUT Long *plCount)
		get_FileSend(OUT Long *plCount)
		get_FileReceived(OUT Long *plCount)
 
		get_BytesSent(OUT Long *plSize)
		get_BytesReceived(OUT Long *plSize)
		get_BytesSent(OUT Long *plSize)
 
		get_BytesSentPerSecondInterval(OUT Long **pplSizePerSec)     // Возвращает массив из Long SizePerSec[200] с посекундной таррификацией      
		get_BytesReceivedPerSecondInterval(OUT Long **pplSizePerSec)
	*/
		[propget, id(1), helpstring("property MessageSent")] HRESULT MessageSent([out, retval] long *pVal);
		[propget, id(2), helpstring("property MessageReceived")] HRESULT MessageReceived([out, retval] long *pVal);
		[propget, id(3), helpstring("property FileSend")] HRESULT FileSend([out, retval] long *pVal);
		[propget, id(4), helpstring("property FileReceived")] HRESULT FileReceived([out, retval] long *pVal);
		[propget, id(5), helpstring("property BytesSent")] HRESULT BytesSent([out, retval] long *pVal);
		[propget, id(6), helpstring("property BytesReceived")] HRESULT BytesReceived([out, retval] long *pVal);
		[propput, id(7), helpstring("property SentPerSecondInterval")] HRESULT BytesSentPerSecondInterval([in] long pVal);
		[propput, id(8), helpstring("property BytesReceivedPerSecondInterval")]
		 HRESULT BytesReceivedPerSecondInterval([in] long pVal);
	}

	[
		object,
		uuid(1D43DD2B-06D1-4D69-AA34-984C74A3EDC1),
		dual,
		helpstring("IConfig Interface"),
		pointer_default(unique)
	]
	interface IConfig : IDispatch
	{
		[propget, id(1), helpstring("property Server")] HRESULT Server([out, retval] BSTR *pVal);
		[propput, id(1), helpstring("property Server")] HRESULT Server([in] BSTR newVal);
		[propget, id(2), helpstring("property Port")] HRESULT Port([out, retval] long *pVal);
		[propput, id(2), helpstring("property Port")] HRESULT Port([in] long newVal);
		[propget, id(3), helpstring("property Path")] HRESULT Path([out, retval] BSTR *pVal);
		[propput, id(3), helpstring("property Path")] HRESULT Path([in] BSTR newVal);
		[propget, id(4), helpstring("property ProxyType")] HRESULT ProxyType([out, retval] long *pVal);
		[propput, id(4), helpstring("property ProxyType")] HRESULT ProxyType([in] long newVal);
		[propget, id(5), helpstring("property ProxyServerName")] HRESULT ProxyServerName([out, retval] BSTR *pVal);
		[propput, id(5), helpstring("property ProxyServerName")] HRESULT ProxyServerName([in] BSTR newVal);
		[propget, id(6), helpstring("property ProxyServerPort")] HRESULT ProxyServerPort([out, retval] long *pVal);
		[propput, id(6), helpstring("property ProxyServerPort")] HRESULT ProxyServerPort([in] long newVal);
		[propget, id(7), helpstring("property UseFirewall")] HRESULT UseFirewall([out, retval] VARIANT_BOOL *pVal);
		[propput, id(7), helpstring("property UseFirewall")] HRESULT UseFirewall([in] VARIANT_BOOL newVal);
		[propget, id(8), helpstring("property FireWallUserName")] HRESULT FireWallUserName([out, retval] BSTR *pVal);
		[propput, id(8), helpstring("property FireWallUserName")] HRESULT FireWallUserName([in] BSTR newVal);
		[propget, id(9), helpstring("property FireWallPassword")] HRESULT FireWallPassword([out, retval] BSTR *pVal);
		[propput, id(9), helpstring("property FireWallPassword")] HRESULT FireWallPassword([in] BSTR newVal);
		[propget, id(10), helpstring("property UseSSL")] HRESULT UseSSL([out, retval] VARIANT_BOOL *pVal);
		[propput, id(10), helpstring("property UseSSL")] HRESULT UseSSL([in] VARIANT_BOOL newVal);
	};
	
	[
		object,
		uuid(9CAE9E38-08D6-44CB-80B6-5BB407829942),
		dual,
		helpstring("IMessages Interface"),
		pointer_default(unique)
	]
	interface IMessages : IDispatch
	{
		[id(1), helpstring("method AddMessage")] HRESULT AddMessage([out, retval] IMessage** ppMessage);

        [propget] HRESULT Count([out, retval] long* pnCount);

        [id(DISPID_VALUE), propget] HRESULT Item([in] long n, [out, retval] IMessage** ppMessage);
        
        [id(DISPID_NEWENUM), propget] HRESULT _NewEnum([out, retval] IUnknown** ppEnum);

	};
	
	[
		object,
		uuid(CEAA7942-7583-45CD-8DD3-34A0C73F2971),
		dual,
		helpstring("IFiles Interface"),
		pointer_default(unique)
	]
	interface IFiles : IDispatch
	{
		[id(1), helpstring("method AddFile")] HRESULT AddFile([out, retval] IFile** ppFile);

        [propget] HRESULT Count([out, retval] long* pnCount);

        [id(DISPID_VALUE), propget] HRESULT Item([in] long n, [out, retval] IFile** ppFile);
        
        [id(DISPID_NEWENUM), propget] HRESULT _NewEnum([out, retval] IUnknown** ppEnum);

	};
	
	[
		object,
		uuid(D0F79DF9-1211-4CCE-8C8A-6E424AA0CADD),
		dual,
		helpstring("IlocalSIDs Interface"),
		pointer_default(unique)
	]
	interface IlocalSIDs : IDispatch
	{
		[id(1), helpstring("method AddSID")] HRESULT AddSID([out, retval] IlocalSID** pplocalSID);

        [propget] HRESULT Count([out, retval] long* pnCount);

        [id(DISPID_VALUE), propget] HRESULT Item([in] long n, [out, retval] IlocalSID** pplocalSID);
        
        [id(DISPID_NEWENUM), propget] HRESULT _NewEnum([out, retval] IUnknown** ppEnum);
	};
	[
		object,
		uuid(C45BE212-F4BF-44BD-B89E-B97D8FC2A58B),
		dual,
		helpstring("IPromos Interface"),
		pointer_default(unique)
	]

	interface IPromos : IDispatch
	{
		[id(1), helpstring("method AddPromo")] HRESULT AddPromo([out, retval] IPromo** ppPromo);

        [propget] HRESULT Count([out, retval] long* pnCount);

        [id(DISPID_VALUE), propget] HRESULT Item([in] long n, [out, retval] IPromo** ppPromo);
        
        [id(DISPID_NEWENUM), propget] HRESULT _NewEnum([out, retval] IUnknown** ppEnum);
	};
	[
		object,
		uuid(8E42793F-62AC-4359-A05B-F9AEA8184EE6),
		dual,
		helpstring("IlocalSID Interface"),
		pointer_default(unique)
	]
	interface IlocalSID : IDispatch
	{
		[propget, id(1), helpstring("property SID")] HRESULT SID([out, retval] BSTR *pVal);
		[propget, id(2), helpstring("property Count")] HRESULT Count([out, retval] long *pVal);
	};
	[
		object,
		uuid(6E966D11-D87B-4E72-937E-C9325B9F0959),
		dual,
		helpstring("IChat Interface"),
		pointer_default(unique)
	]
	interface IChat : IDispatch
	{
		[propget, id(DISPID_VALUE), helpstring("property Value")] HRESULT Value([in] BSTR bsName, [out, retval] VARIANT *pVal);
		[id(1), helpstring("method SetStatus")] HRESULT SetStatus([in] long Status, [in] long Param, [out] long* Handle);
		[id(2), helpstring("method CreateMessage")] HRESULT CreateMessage([out,retval] IMessage** ppMessage);
		[id(3), helpstring("method AddUser")] HRESULT AddUser([in] long UserID);
		[id(4), helpstring("method Invite")] HRESULT Invite([in] BSTR Invitation ,[out, retval] long * Handle);
		[id(5), helpstring("method Leave")] HRESULT Leave([out, retval] long * Handle);
		[id(7), helpstring("method Edit")] HRESULT Edit([in] BSTR Name, [in] BSTR Descr, [out, retval] long* Handle);
		[id(6), helpstring("method Accept")] HRESULT Accept([in] long Result, [out, retval] long* Handle);
	};
	[
		object,
		uuid(90D29286-317A-4895-AAC2-449463E10DB3),
		dual,
		helpstring("IChats Interface"),
		pointer_default(unique)
	]
	interface IChats : IDispatch
	{
		[id(1), helpstring("method AddChat")] HRESULT AddChat([out, retval] IChat** ppChat);

        [propget] HRESULT Count([out, retval] long* pnCount);

        [id(DISPID_VALUE), propget] HRESULT Item([in] long n, [out, retval] IChat** ppChat);
        
        [id(DISPID_NEWENUM), propget] HRESULT _NewEnum([out, retval] IUnknown** ppEnum);
	};

	[
		uuid(567B302A-1DBF-4A75-8E46-65F54A58D91D),
		helpstring("Session Class")
	]
	coclass Session
	{
		[default] interface ISession;
		[default, source] dispinterface _ISessionEvents;
	};
/*	[
		uuid(12177FE2-D4D5-4E92-A430-D8FC3845774C),
		helpstring("User Class")
	]
	coclass User
	{
		[default] interface IUser;
	};
	[
		uuid(EB496DD1-E0DF-41FA-B63C-D7BA7D9FF3D5),
		helpstring("Users Class")
	]
	coclass Users
	{
		[default] interface IUsers;
	};
	
	[
		uuid(A998B391-B30C-4101-BCE2-97067098C26C),
		helpstring("CallBackEvents Class")
	]
	coclass Promo
	{
		[default] interface IPromo;
	};
	[
		uuid(D51400C0-A338-4D2E-B4CB-159CF7579909),
		helpstring("Message Class")
	]
	coclass Message
	{
		[default] interface IMessage;
	};
	[
		uuid(0CA7B601-2FA5-40AA-8666-56F083020345),
		helpstring("File Class")
	]
	coclass File
	{
		[default] interface IFile;
	};
	
	[
		uuid(5CA6E67E-4F0C-407E-A38C-4E564C34487F),
		helpstring("Config Class")
	]
	coclass Messages
	{
		[default] interface IMessages;
	};
	
	[
		uuid(F3630615-5516-4FB5-A299-378F13D9F414),
		helpstring("Files Class")
	]
	coclass Files
	{
		[default] interface IFiles;
	};
	
	[
		uuid(0E5C97B4-2B69-4355-88A6-2983F43276B3),
		helpstring("localSIDs Class")
	]
	coclass localSIDs
	{
		[default] interface IlocalSIDs;
	};
	[
		uuid(2BA2E731-4462-43D2-A5AB-6AB47B0704F7),
		helpstring("Promos Class")
	]
	coclass Promos
	{
		[default] interface IPromos;
	};
	[
		uuid(98E50CDC-5A97-48D7-98E7-3CBF7FF6A2A0),
		helpstring("localSID Class")
	]
	coclass localSID
	{
		[default] interface IlocalSID;
	};*/
/*	[
		uuid(7F7B7695-3F06-409B-8B2E-F922FB708D82),
		helpstring("Chat Class")
	]
	coclass Chat
	{
		[default] interface IChat;
	};
	[
		uuid(9359EDFF-2973-4BB3-AC7A-E9A77DEE93B0),
		helpstring("Chats Class")
	]
	coclass Chats
	{
		[default] interface IChats;
	};*/
};
