//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OfsTv.rc
//
//#define IDR_MANIFEST                    1
#define ID_AUTHORIZATION_REQUEST        2
#define IDC_OFFLINE_BUTTON              3
#define IDCANCEL2                       3
#define ID_GETUSERDETAILS_BUTTON        3
#define IDC_DELETE_BUTTON               4
#define IDC_GOTODIR_BUTTON              4
#define IDC_REMEMBERLATER_BUTTON        5
#define IDD_ABOUTBOX                    100
#define ID_DOC_WINDOW                   101
#define ID_DOC_WINDOW2                  102
#define IDC_SEARCHBAR                   103
#define IDC_STATUSBAR                   104
#define IDE_EDIT                        108
#define ID_OFS_MESSENGER                109
#define ID_COOTREE_CTRL                 110
#define IDD_DIALOG_MESSAGE_COME         111
#define IDC_DHTML_EDIT                  112
#define ID_NETWORK_STATUS               113
#define IDS_DISCONNECT                  113
#define ID_USER_LOGIN                   114
#define IDS_NOTLOGIN                    114
#define IDC_DOWNLOAD_TIMER              115
#define IDS_OFFLINE                     115
#define IDC_UPLOAD_TIMER                116
#define IDS_CONNECTING                  116
#define IDS_CONNECTED                   117
#define IDS_ONLINE                      118
#define IDS_INVISIBLE                   119
#define IDS_DND                         120
#define IDS_AWAY                        121
#define IDB_HIDEMPA                     121
#define IDS_NA                          122
#define IDB_SENDMESSSAGE                122
#define IDS_OCCUPIED                    123
#define IDB_SENDFILE                    123
#define IDS_AWAITING                    124
#define IDB_ADDPEOPLE                   124
#define IDS_UNKNOWN                     125
#define IDB_LOGO                        125
#define IDS_STATUSNAME                  126
#define ID_DBLCLK_TRAY                  126
#define IDS_USERNAME                    127
#define ID_HISTORY                      127
#define IDR_MAINFRAME                   128
#define IDP_PROGRESS                    128
#define IDR_OFSTVTYPE                   129
#define IDS_NETWORK_STATUS              129
#define IDC_FONTNAME                    129
#define IDS_USER_LOGIN                  130
#define IDT_AUTOCHANGETIMER             130
#define IDS_USER_STATUS                 131
#define IDS_NETOPTIONS                  131
#define IDB_MESSAGE                     131
#define IDS_ACCESSTYPE                  132
#define IDB_SR                          132
#define IDS_PROXYNAME                   133
#define ID_EXWINDOW_BROWSER             133
#define IDS_PROXYPORT                   134
#define ID_LCLK_TRAY                    134
#define IDS_LOGIN                       135
#define IDC_BUTTON_CREATE               135
#define IDS_NICKNAME                    136
#define IDC_BUTTON_DELETE               136
#define IDS_PASSWORD                    137
#define IDR_OFS_MENU                    137
#define IDC_BUTTON_VIEW                 137
#define IDS_REMEMBER                    138
#define IDC_BUTTON_UP                   138
#define IDD_DIALOG_MESSAGE_SEND         139
#define IDS_BYPASSENABLE                139
#define IDT_LOADNOTSENDMESSAGES         139
#define IDS_OFSMESSENGER                140
#define IDS_FLOATCX                     141
#define IDS_FLOATCY                     142
#define IDS_BOLD                        143
#define IDS_ITALIC                      144
#define IDS_UNDERLINE                   145
#define IDB_UNDERLINE                   146
#define IDS_SIZE                        146
#define IDB_COLOR                       147
#define IDS_FONT                        147
#define IDB_ITALIC                      148
#define IDS_COLUMN_WIDTH                148
#define IDB_BOLD                        149
#define IDS_MESSAGES                    149
#define IDS_MAIN                        150
#define IDS_SPLITRECT                   151
#define IDD_DOWNLOAD_DIALOG             152
#define IDS_SENDRECT                    152
#define IDD_DIALOG_FILE_UPLOAD          153
#define IDS_COMERECT                    153
#define IDR_MESSENGER_MENU              154
#define IDS_HISTORY                     154
#define IDS_HISTORY_FOLDER              155
#define IDD_DIALOG_LOGIN                156
#define IDS_MODE                        156
#define IDS_SORT                        157
#define IDS_SYNCHRONIZE                 158
#define IDS_MESSSAGEMODE                159
#define IDD_ADDUSER_DIALOG              160
#define IDS_FROMTIME                    160
#define IDS_TOTIME                      161
#define IDD_DIALOG_USER_DETAILS         162
#define IDS_SYNCMODE                    162
#define IDS_BANDWIDTH                   163
#define IDD_NETOPTION_DIALOG            164
#define IDS_SHOWNEW                     164
#define IDD_MESSAGE_DIALOG              165
#define IDS_USERDELETE                  165
#define IDS_ADDTOIGNORY                 166
#define IDS_FLOATING                    167
#define IDS_ANIMATION                   168
#define IDS_HIDEINTRAY                  169
#define IDI_NEWMESSAGE                  170
#define IDI_EMPTY                       171
#define IDD_DIALOG_MESSAGE_SPLIT        172
#define IDD_SCREENSHOT_DIALOG           173
#define IDD_DIALOG_HISORY               174
#define IDT_MCSCREENCAPTUREEX           174
#define IDD_DIALOG_MESSAGE_SPLIT2       178
#define IDD_DIALOG_MESSAGE_SEND2        180
#define IDD_PAGE_MES_GENERAL            183
#define IDD_PAGE_MES_SYNCHRONIZE        184
#define IDD_PAGE_MPA_BANDWIDTH          185
#define IDD_DIALOG_MESSAGE_COME2        186
#define IDB_BITMAP1                     190
#define IDB_LOGO_BITMAP                 190
#define IDR_MESYAHOOSPLITDLG            198
#define IDS_DIALOGMODE                  199
#define IDS_SOUNDOFF                    200
#define IDS_ICQSPLITTER_POS             201
#define IDS_SETAWAY_ENABLE              202
#define IDD_HISTORYYAHOODLGBAR          203
#define IDS_SETNA_ENABLE                203
#define IDS_SETAWAY                     204
#define IDD_SENDMESSAGEYAHOODLGBAR      205
#define IDS_SETNA                       205
#define IDD_PAGE_DIALOGMODE             206
#define IDS_MCSPLITTER_POS              206
#define ID_DHTML_CTRL                   207
#define IDS_AUTOLOGON                   207
#define IDR_FONTEDITYAHOOBAR            208
#define IDS_USEFIREWALL                 208
#define IDS_FIREWALLUSER                209
#define IDS_FIREWALLPASS                210
#define IDS_CANTADDUSER                 211
#define IDS_CLMODE                      212
#define IDS_SHOWOFFLINEFILES            213
#define IDB_BITMAP2                     214
#define IDB_SMILES                      214
#define IDS_INFO                        214
#define IDD_SETTINGS                    215
#define IDS_LOGOVERSION                 215
#define IDD_DIALOG_MESSAGE_SPLIT_ICQ    216
#define IDS_FILEMANAGER                 216
#define IDS_FILE_DESCRIPTION            217
#define ID_AUTOKILLER                   218
#define IDS_ADD_FRIEND                  218
#define IDB_BUTTONIMAGE                 219
#define IDS_ADD_FRIENDR                 219
#define IDC_SPLITV                      220
#define IDS_FINDUSER                    220
#define IDD_DIALOG_MESSAGE_SEND_ICQ     221
#define IDS_EXWINDOW                    221
#define IDS_USERDETAILS                 222
#define IDS_ENTER                       223
#define IDB_TRAYSTATUS_BITMAP           224
#define IDS_CTRLENTER                   224
#define IDD_PAGE_STATUS_MODE            225
#define IDS_ALTENTER                    225
#define IDD_PAGE_CONECTIONS             226
#define IDS_SHIFTENTER                  226
#define IDD_DIALOG_MESSAGE_SPLIT3       227
#define IDS_ALTS                        227
#define IDS_CTRLS                       228
#define IDS_GROUPSENDMESSAGE            229
#define IDD_DELUSER_DIALOG              230
#define IDS_GROUPSENDFILE               230
#define IDD_ADDUSERREQUEST_DIALOG       231
#define IDS_KEEPTOP                     231
#define IDB_DOWNLOAD_FILESTATUS         232
#define IDS_SOUND                       232
#define IDD_PAGE_CONTACTLIST            233
#define IDS_INCOMING_MESSAGE            233
#define IDD_FILEDESCRIPTION_DIALOG      234
#define IDS_INCOMING_FILE               234
#define IDS_ONLINE_ALERT                235
#define IDC_CURSOR1                     236
#define IDC_HANDCURSOR                  236
#define IDS_STARTUP                     236
#define IDD_NETOPTIONS_2                237
#define IDS_USER_OFFLINE                237
#define IDS_AUTHORIZATION_REQUEST       238
#define IDS_COMMON                      239
#define IDS_STUBS                       240
#define IDS_RECEIVED_FILES              241
#define IDB_TREECHECK                   242
#define IDS_CLEARCHATWINDOW             242
#define IDD_WEB_WINDOW                  243
#define IDS_SHOWFRIENDSSTATUS           243
#define IDS_MYDOCUMENTS                 244
#define IDB_SMILE                       245
#define IDS_OUTGOING_FILE               245
#define IDD_FILEMANAGER_DIALOG          246
#define IDS_ALERT_DIALOG                246
#define IDS_NEW_ALERT_COME              246
#define IDS_BAD_FILE                    247
#define IDS_SERVICENOTAVAILABLE         248
#define IDS_LICENSE_LIMIT               249
#define IDD_UPLOADFILE_DIALOG           250
#define IDS_LOCDATABASE_ADDMESSAGE_ERROR 250
#define IDS_LOCDB_REINDEX_ERROR         251
#define IDS_REINDEX                     252
#define IDS_LOCDB_GLOABL_ERROR          253
#define IDD_PAGE_EDIT                   254
#define IDS_LOCDB_FIXED_PROBLEM         254
#define IDD_PREFERENCES                 255
#define IDS_FILES_SEND_LIMIT            255
#define IDS_ADD_FRIEND_TITLE            256
#define IDS_AUTH_CANCEL_FORMAT          257
#define IDD_GROUP_MESSAGE_SEND_DIALOG   258
#define IDS_CONTACTLIST_DEL_FORMAT      258
#define IDS_IGNORYLIST_DEL_FORMAT       259
#define IDS_VERSION_FORMAT              260
#define IDD_GROUP_FILE_SEND_DIALOG      261
#define IDS_SERVER_VERSION              261
#define IDS_CLOSE_BTN_NAME              262
#define IDS_ALL_FILES_FORMAT            263
#define IDS_SELECT_FOLDER_NAME          264
#define IDD_TV                          265
#define IDS_FILENAME_NAME               265
#define IDS_SENDER_NAME                 266
#define IDD_PAGE_MES_SOUND              267
#define IDS_STATUS_NAME                 267
#define IDD_PAGE_MES_ALERT              268
#define IDS_PROGRESS_NAME               268
#define IDD_PAGE_STUBS                  269
#define IDS_DATE_NAME                   269
#define IDS_FILESIZE_NAME               270
#define IDD_FILES_EXPLORER              271
#define IDS_DESCRIPTION_NAME            271
#define IDS_IBN_FILE_MANAGER_NAME       272
#define IDC_SPLITH                      273
#define IDS_CANT_LOAD_OFFLINE_FILES     273
#define IDD_FLOAT_MESSAGE               274
#define IDS_OPEN_FILE_ERROR_NAME        274
#define IDD_POPUP_MESSAGE               275
#define IDS_FILETYPE_NAME               275
#define IDD_MAIN                        276
#define IDS_FILEMODIFIED_NAME           276
#define IDD_WEB_WINDOW1                 277
#define IDD_WEB_WINDOW_CHILD            277
#define IDS_RECIPIENT_NAME              277
#define IDS_APPDATA_NAME                278
#define IDS_APP_NAME                    279
#define IDS_CANT_UPLOAD_FILE_ERROR_FORMAT 280
#define IDS_DATA_BYTE_FORMAT            281
#define IDS_DATA_KBYTE_FORMAT           282
#define IDD_MCUPDATE_DIALOG             283
#define IDS_DATA_MBYTE_FORMAT           283
#define IDR_SEND_DATA_AVI               284
#define IDS_IBN_RECEIVED_FILE_NAME      284
#define IDI_CHECK_ICON                  285
#define IDS_COLLAPSE_NAME               285
#define IDS_EXPAND_NAME                 286
#define IDD_SELECT_SERVER_DIALOG        287
#define IDS_NEW_CHILD_FOLDER_NAME       287
#define IDS_FRIENDS_NAME                288
#define IDS_HISTORY_SYNC_NAME           289
#define IDD_CHAT_DIALOG                 289
#define IDS_IBN_UPDATE_TITLE            290
#define IDS_IBN_UPDATE_ERROR_TITLE      291
#define IDD_CHAT_CREATE                 291
#define IDS_IBN_UPDATE_ERROR2_TITLE     292
#define IDD_DELCHAT_DIALOG              292
#define IDS_IBN_LOGIN_TITLE             293
#define IDD_PAGE_CHAT                   293
#define IDS_TRAY_TOOLTIP_FORMAT         294
#define IDD_INVITE_CHAT_DIALOG          294
#define IDS_INSTANT_DIRECTORY_NAME      295
#define IDS_DEFAULT_NAME                296
#define IDD_MONITOR_DIALOG              296
#define IDS_REQUEST_DENIED_FORMAT       297
#define IDS_REQUEST_ACCEPT_FORMAT       298
#define IDD_GROUP_ASSIGN_TODO           298
#define IDS_IBN_ADD_FRIEND_TITLE        299
#define IDS_MAIN_TITLE_FORMAT           300
#define IDS_ERROR_TITLE                 301
#define IDS_GENERAL_NAME                302
#define IDS_STATUS_MODE_NAME            303
#define IDC_SELECTCURSOR                303
#define IDS_CONNECTION_NAME             304
#define IDC_HANDCATCHCURSOR1            304
#define IDS_ALERTS_NAME                 305
#define IDC_HANDCATCHCURSOR2            305
#define IDS_SOUNDS_NAME                 306
#define IDC_PENCURSOR                   306
#define IDS_APPLICATION_NAME            307
#define IDD_PAGE_MES_TEMPLATE           307
#define IDS_EDIT_NAME                   308
#define IDD_EDIT_MES_TEMPLATE_DIALOG    308
#define IDS_SHOW_CONTACTLIST_NAME       309
#define IDC_TEXTCURSOR                  309
#define IDS_IBN_UPDATE_LIST_NAME        310
#define IDD_DIALOG_COMMENTSETTINGS      310
#define IDS_CANT_SAVE_SETTINGS_NAME     311
#define IDD_SELECTSMILE_DIALOG          311
#define IDS_USER_IS_FORMAT              312
#define IDS_FROM_FORMAT                 313
#define IDS_INSTANT_CHAT_TITLE_FORMAT   314
#define IDS_APP_NAME_INFO_NAME          315
#define IDS_APP_VER_NAME                316
#define IDS_SOUND_FORMAT                317
#define IDS_SOUND_EVENT                 318
#define IDS_SOUND_FILE_NAME             319
#define IDS_TIP_CLOSE                   320
#define IDS_TIP_MAXIMIZE                321
#define IDS_TIP_RESTORY                 322
#define IDS_TIP_MINIMIZE                323
#define IDS_TIP_BACK                    324
#define IDS_TIP_FORWARD                 325
#define IDS_TIP_STOP                    326
#define IDS_TIP_REFRESH                 327
#define IDS_WEBBROWSER_TITLE_FORMAT     328
#define IDS_LOADING_NAME                329
#define IDS_SHOWNAME_FORMAT             330
#define IDS_ADD_USER_ERROR              331
#define IDS_DEL_USER_ERROR              332
#define IDS_NEWFOLDER_FORMAT            333
#define IDS_NEWFOLDERN_FORMAT           334
#define IDS_HOSTORY_TITLE_FORMAT        335
#define IDS_SYNC_HISTORY_ERROR_NAME     336
#define IDS_SYNC_HISTORY_COMPLETED_NAME 337
#define IDS_AUTOUPDATE_CLOSE_NAME       338
#define IDS_DO_CLOSE_NAME               339
#define IDS_OPEN_FILE_NAME              340
#define IDS_USER_ALLREADY_IN_CONTACTLIST_NAME 341
#define IDS_FLOATING_OFF_NAME           342
#define IDS_FLOATING_ON_NAME            343
#define IDS_DETAILS_FOR_FORMAT          344
#define IDS_USER_DETAILS_TITLE          345
#define IDS_SHOW_ALERT_MESAGE_FORMAT    346
#define IDS_FILE_INCOMPLETE_NAME        347
#define IDS_FILE_COMPLETE_NAME          348
#define IDS_FILE_EMPTY                  349
#define IDS_FILE_WAIT_NAME              350
#define IDS_FILE_START_NAME             351
#define IDS_FILE_CANCEL_NAME            352
#define IDS_FILE_ERROR_NAME             353
#define IDS_FILE_NEW_NAME               354
#define IDS_FILE_OFFLINE_NAME           355
#define IDS_FILE_DOWNLOADED_NAME        356
#define IDS_TIME_SEC_FORMAT             357
#define IDS_FILEL                       358
#define IDS_REMOVE_FROM_TASK_BAR        359
#define IDS_FILE_PUBLISHED_NAME         360
#define IDS_CANT_UPLOAD_FILE_ERROR_2_FORMAT 361
#define IDS_SHOW_CHAT_CONTACTLIST_NAME  362
#define IDS_INACTIVE_CHAT               363
#define IDS_ACTIVE_CHAT                 364
#define IDS_CHAT_SHOW_NAME              365
#define IDS_CREATE_NEW_CONFERENCE       366
#define IDS_CHAT_DEL_FORMAT             367
#define IDS_CHATLOADMESS                368
#define IDS_CONFERENCE_NAME             369
#define IDS_INVITE_CHAT                 370
#define IDS_INVITED_MESSAGE             371
#define IDS_LEAVED_MESSAGE              372
#define IDS_ACCEPT_CHAT_ERROR           373
#define IDS_UPDATE_CONFERENCE           373
#define IDS_INVITE_CONFERENCE           374
#define IDS_CONFERENCE_CAPTION_TEXT     375
#define IDS_ACCEPT_MESSAGE              376
#define IDS_DENY_MESSAGE                377
#define IDS_SELECT_COLOR                378
#define IDS_DOCS_NAME                   379
#define IDS_LINKS_NAME                  380
#define IDS_NEWS_NAME                   381
#define IDS_CHANGE_COLOR                382
#define IDD_INVITE_CHAT_DIALOG_TEXT     383
#define IDS_DETAILS_CONFERENCE          384
#define IDS_INVALID_CONFERENCE_NAME     385
#define IDS_CHAT                        386
#define IDS_CHATSPLITRECT               387
#define IDS_CONFERENCE_MENU             388
#define IDS_INVALID_INVITE_NAME         389
#define IDS_FEW_USER_STRING             390
#define IDS_WEB_FOLDER_VEW              391
#define IDS_WEB_FOLDERS_NAME            392
#define IDS_INVITE_CHAT_NICK_NAME       393
#define IDS_TIP_CREATE_FOLDER           394
#define IDS_TIP_DELETE                  395
#define IDS_TIP_VIEWS                   396
#define IDS_TIP_UP                      397
#define IDS_TIP_MENU                    398
#define IDS_TIP_OPTIONS                 399
#define IDS_TIP_FONT_COLOR              400
#define IDS_TIP_BOLD                    401
#define IDS_TIP_ITALIC                  402
#define IDS_TIP_UNDERLINE               403
#define IDS_TIP_SMILES                  404
#define IDS_TIP_FONT                    405
#define IDS_TIP_FONT_SIZE               406
#define IDS_INVITE_TO_MENU_ITEM         407
#define IDS_GROUPS_STATE                408
#define IDS_WEB_OPTIONS                 409
#define IDS_WEB_MYDETAILS               410
#define IDS_WEB_USERDETAILS             411
#define IDS_WEB_ALERTLIST               412
#define IDS_WEB_IBNTODAY                413
#define IDS_WEB_CHATDETAILS             414
#define IDS_WEB_CHATHISTORY             415
#define IDS_USESSL                      416
#define IDS_INVITECHAT_ERROR            417
#define IDS_MESSAGES_SENT               418
#define IDS_MESSAGES_RECEIVED           419
#define IDS_FILE_SENT                   420
#define IDS_FILE_RECEIVED               421
#define IDS_KILOBYTES                   422
#define IDS_SECONDS                     423
#define IDS_TOTAL_SENT                  424
#define IDS_TOTAL_RECEIVED              425
#define IDS_TOTAL_COST                  426
#define IDS_COST                        427
#define IDS_COSTTYPE                    428
#define IDS_SHOW_LINE_TOTAL             429
#define IDS_SHOW_LINE_SENT              430
#define IDS_SHOW_LINE_RECEIVED          431
#define IDS_VIEWMODE                    432
#define IDS_SHOW_IBN_ACTIONS_NAME       433
#define IDS_IBNACTIONBROWSWER           434
#define IDS_IBNACTIONBROWSER            434
#define IDS_OPENINMAXIMAZE              435
#define IDS_GROUPASSIGNTODO             436
#define IDS_WEB_ASSIGN_TODO             437
#define IDS_ASSIGN_TODO                 438
#define IDS_SYSTEM_SERVICES_GROUP_NAME  439
#define IDS_SCREEN_CAPTURE              440
#define IDS_SCREEN_CAPTURE_NAME         441
#define IDS_TIP_UNDO                    442
#define IDS_TIP_SAVE                    443
#define IDS_TIP_REDO                    444
#define IDS_TIP_MOVE                    445
#define IDS_TIP_CROP                    446
#define IDS_TIP_ZOOMOUT                 447
#define IDS_TIP_ZOOMIN                  448
#define IDS_TIP_TEXT                    449
#define IDS_TIP_PEN                     450
#define IDS_TIP_PENCOLOR                451
#define IDS_PENCOLOR                    452
#define IDS_TIMEFILTER_ALL              453
#define IDS_TIMEFILTER_TODAY            454
#define IDS_TIMEFILTER_YESTERDAY        455
#define IDS_TIMEFILTER_THISWEEK         456
#define IDS_TIMEFILTER_LASTWEEK         457
#define IDS_TIMEFILTER_THISMONTH        458
#define IDS_TIMEFILTER_LASTMONTH        459
#define IDS_TIMEFILTER_THISYEAR         460
#define IDS_TIMEFILTER_LASTYEAR         461
#define IDS_TIMEFILTER_CUSTOM           462
#define IDS_TIMEFILTER                  463
#define IDS_FROMTIME_FILTER             464
#define IDS_TOTIME_FILTER               465
#define IDS_CAPTURE_ACTION_SENDTO       466
#define IDS_CAPTURE_ACTION_ASSIGNTODO   467
#define IDS_CAPTURE_ACTION_PUBLISH      468
#define IDS_CAPTURE_ACTION_CREATEISSUE  469
#define IDS_CAPTURE_ACTION_TREEHEADER   470
#define IDS_LOGIN_TOOLTIP_CAPTION       471
#define IDS_LOGIN_TOOLTIP_BODY          472
#define IDS_SHOWOFFLINE_USERS           473
#define IDS_MINIMIZE_ONCLOSE            474
#define IDS_MESSAGE_TEMPLATES_NAME      475
#define IDS_TEMPLATE_NAME               476
#define IDS_TEMPLATE_TEXT               477
#define IDS_MESSAGE_TEMPLATES_REG       478
#define IDS_DEFAULT_MES_TEMPLATE_XML    479
#define IDS_SEND_MESSAGE_TEMPLATE_AUTO  480
#define IDS_TEXTCOLOR                   481
#define IDS_TEXTSIZE                    482
#define IDS_FONTNAME                    483
#define IDS_GET_DEFAULT_BROWSER_FROM_REGISTRY 484
#define IDS_SMILES_MORE                 485
#define IDS_CONTACTLIST_SORT_BY_FIRSTNAME 486
#define IDS_DHTML_CREATE_ERROR_MGS      487
#define IDS_UPDATE_AUTOCHECK            488
#define IDS_UPDATE_AUTOCHECK_TIME       489
#define IDC_SEND_BUTTON                 1001
#define IDC_EDIT_FRAME                  1003
#define IDC_COLOR_BUTTON                1006
#define IDC_NEXT_BUTTON                 1007
#define IDC_ANSWER_BUTTON               1008
#define IDC_DOWNLOAD_BUTTON             1008
#define IDC_FILE_DOWNLOAD_LIST          1009
#define IDC_OPEN_BUTTON                 1009
#define IDC_DELETEFILE_BUTTON           1010
#define IDC_UPLOAD_BUTTON               1011
#define IDC_CANCEL_BUTTON               1012
#define IDC_FILE_UPLOAD_LIST            1013
#define IDC_CANCEL_BUTTON2              1013
#define IDC_OK_BUTTON                   1013
#define IDC_LOGIN_EDIT                  1016
#define IDC_EDIT_LOGIN                  1016
#define IDC_PASSWORD_EDIT               1017
#define IDC_EDIT_PASSWORD               1017
#define IDC_REMEMDER_CHECK              1018
#define IDC_SELLER_CHECK                1020
#define IDC_BUYER_CHECK                 1021
#define IDC_NICK_EDIT                   1024
#define IDC_ROLE_EDIT                   1025
#define IDC_LAST_EDIT                   1026
#define IDC_EMAIL_EDIT                  1027
#define IDC_COMPANY_EDIT                1028
#define IDC_FIRST_EDIT                  1029
#define ID_AUTHORIZATION                1031
#define IDC_TICKERCTRL                  1032
#define IDC_LOAD_MORE                   1033
#define IDC_REMEMBER_BUTTON             1034
#define IDC_BUTTON_REMEMBER             1034
#define ID_OK                           1035
#define IDC_SHOWCHECK                   1038
#define IDC_MESSAGE_EDIT                1039
#define IDC_DEFAULT_RADIO               1041
#define IDC_DIRECT_RADIO                1042
#define IDC_PROXY_RADIO                 1043
#define IDC_SERVERNAME                  1044
#define IDC_SERVERPORT                  1045
#define IDC_NETOPTION                   1046
#define IDC_SERVERNAME2                 1046
#define IDC_FIREWALLUSER                1046
#define IDC_BUTTON_NETOPTIONS           1046
#define IDC_FIREWALLPASS                1047
#define IDC_BYPASSCHECK                 1048
#define IDC_DEMOSIGNIN                  1049
#define IDC_FORGOTH                     1050
#define IDC_ADDNEWUSER                  1051
#define IDC_HISTORY_EXPLORER            1054
#define IDC_HISTORYFRAME                1056
#define IDC_INCOMING                    1057
#define IDC_OUTGOING                    1058
#define IDC_DIALOG                      1059
#define IDC_LASTFIRST                   1060
#define IDC_MCCLOSE                     1063
#define IDC_MCSEND                      1064
#define IDC_MCCANCEL                    1064
#define IDC_MCDENY                      1064
#define IDC_USERINFO                    1065
#define IDC_MCADDTOCONTACT              1065
#define IDC_SENDERUSERINFO              1066
#define IDC_MCSELECTALL                 1066
#define IDC_MCUNSELECTALL               1067
#define IDC_BTN_USERS                   1067
#define IDC_SINGLE_RADIO                1068
#define IDC_SEND_DELETE                 1068
#define IDC_MCACCEPT                    1068
#define IDC_MCMAXI                      1068
#define IDC_BTN_SEND                    1068
#define IDC_BTN_FILES                   1068
#define IDC_SPLIT_RADIO                 1069
#define IDC_SEND_CANCEL                 1069
#define IDC_MCUSERDETAILS               1069
#define IDC_BTN_SELECT_ALL              1069
#define IDC_DAY_RADIO                   1070
#define IDC_SEND_UPLOAD                 1070
#define IDC_BTN_SELECT_NONE             1070
#define IDC_MCCHATDETAILS               1070
#define IDC_WEEK_RADIO                  1071
#define IDC_DOWN_OFFLINE                1071
#define IDC_MONTH_RADIO                 1072
#define IDC_DOWN_REMLATER               1072
#define IDC_YEAR_RADIO                  1073
#define IDC_DOWN_DELETE                 1073
#define IDC_CUSTOM_RADIO                1074
#define IDC_DOWN_CANCEL                 1074
#define IDC_DOWN_DOWNLOAD               1075
#define IDC_DOWN_SHOWOFFLINE            1076
#define IDC_MCMAXI2                     1077
#define IDC_FROM_DATETIMEPICKER         1078
#define IDC_BTN_LIBRARY                 1078
#define IDC_BTN_RECEIVED                1079
#define IDC_TO_DATETIMEPICKER           1080
#define IDC_BTN_SENT                    1080
#define IDC_LOW_RADIO                   1081
#define IDC_MEDIUM_RADIO                1082
#define IDC_BROADBAND_RADIO             1083
#define IDC_SHOWNEWMESSAGE_CHECK        1084
#define IDC_MCNEXTMESSAGE               1085
#define IDC_MCANSWER                    1086
#define IDC_MCOK                        1087
#define IDC_MCOPTIONS                   1089
#define IDC_ANIMATION_CHECK             1090
#define IDC_MCMENU                      1090
#define IDC_HIDEMPAINTRAY_CHECK         1091
#define IDC_COMPANY_STATIC              1091
#define IDC_MCCHECKSEND                 1091
#define IDC_BUILD_STATIC                1092
#define IDC_HIDEMPAINTRAY_CHECK2        1092
#define IDC_KEEPTOP_CHECK               1092
#define IDC_MCCHECKISSUE                1092
#define IDC_VERSION_STATIC              1093
#define IDC_MCCHECKTODO                 1093
#define IDC_LOGO_STATIC                 1094
#define IDC_VERSION_STATIC2             1094
#define IDC_SERVER_VERSION_STATIC       1094
#define IDC_MCCHECKPUBLISH              1094
#define IDC_RECEPIENT_EDIT              1095
#define IDC_SENDER_EDIT                 1097
#define IDC_MESSAGESTATIC               1101
#define IDC_MCMESSENGER_SUNDANCEEDITION_RADIO 1102
#define IDC_MCMESSENGER_RADIO           1103
#define IDC_YAHOO_RADIO                 1104
#define IDC_BUTTON_APPLY                1105
#define IDC_MCMESSENGER_RADIO2          1105
#define IDC_ICQ_RADIO                   1105
#define IDC_LIST                        1106
#define IDC_PLACEHOLDER                 1107
#define IDC_USERDETAILS_BUTTON          1109
#define IDC_SOUNDONOFF_BUTTON           1110
#define IDC_SELECTPATH_BUTTON           1110
#define IDC_SPELLCHECKING_BUTTON        1111
#define IDC_INSERTSMILEY_BUTTON         1112
#define IDC_INSERTEMOTION_BUTTON        1113
#define IDC_TEXTFONT_BUTTON             1114
#define IDC_TEXTCOLOR_BUTTON            1115
#define IDC_NICK_STATIC                 1116
#define IDC_EMAIL_STATIC                1117
#define IDC_CHARS_STATIC                1118
#define IDC_TALK_BUTTON                 1119
#define IDC_MESSAGE_CHECK               1120
#define IDC_SMS_CHECK                   1121
#define IDC_EMAIL_CHECK                 1122
#define IDC_MESSAGEBKGR_BUTTON          1123
#define IDC_MESSAGE_FRAME               1124
#define IDC_AVI_FRAME                   1125
#define IDC_SPLITTER_STATIC             1126
#define IDC_SENDBYSTATIC                1128
#define IDC_CHARSDESC_STATIC            1129
#define IDC_EMAILDESC_STATIC            1130
#define IDC_USERMENU_BUTTON             1131
#define IDC_MSGMODE_BUTTON              1132
#define IDC_HISTORY_BUTTON              1133
#define IDC_SEPARATOR1_STATIC           1134
#define IDC_SEPARATOR2_STATIC           1135
#define IDC_MULTIPLESEND_BUTTON         1136
#define IDC_RETRY_BUTTON                1137
#define IDC_MULTIPLE_RECEPIENTS_TREE    1139
#define IDC_TOSTATIC                    1140
#define IDC_MULTISTATIC                 1141
#define IDC_SELECTRECEPIENT_STATIC      1141
#define IDC_SETAWAY_CHECK               1143
#define IDC_SETNA_CHECK                 1144
#define IDC_SETAWAYMINUTES_EDIT         1145
#define IDC_SETNAMINUTES_EDIT           1146
#define IDC_SETAWAY_SPIN                1147
#define IDC_SETAWAY_STATIC              1148
#define IDC_SETNA_SPIN                  1149
#define IDC_SETNA_STATIC                1150
#define IDC_TIME_STATIC                 1151
#define IDC_LAUNCHONSTART_CHECK         1152
#define IDC_AUTOCONNECT_CHECK           1153
#define IDC_USEFIREWALL_CHECK           1154
#define IDC_USESSL_CHECK                1156
#define IDC_DESCRIPTION_STATIC          1157
#define ID_DANY                         1158
#define IDC_SHOWOFFLINEFILES_CHECK      1159
#define IDC_CLMODE1_RADIO               1160
#define IDC_CLMODE2_RADIO               1161
#define IDC_FILEDESCRIPTION_EDIT        1162
#define IDC_BUTTON_OK                   1169
#define IDC_BUTTON_CANCEL               1170
#define IDC_BUTTON_X                    1171
#define IDC_RADIO_1                     1172
#define IDC_BUTTON_ALERTS               1172
#define IDC_BUTTON_CANCEL2              1172
#define IDC_RADIO_2                     1173
#define IDC_BUTTON_APPS                 1173
#define IDC_RADIO_3                     1174
#define IDC_BUTTON_FILES                1174
#define IDC_BUTTON_DIRECTORY            1175
#define IDC_USESSLCHECKBOX              1175
#define IDC_EDIT_USER                   1176
#define IDC_EDIT_PASS                   1177
#define IDC_EDIT_SERV                   1178
#define IDC_EDIT_PORT                   1179
#define IDC_SHOWOFFLINECHECK            1180
#define IDC_SENDERNAME_EDIT             1181
#define IDC_CREATEOFFLINEFOLDER         1181
#define IDC_FILENAME_EDIT               1182
#define IDC_SIZE_EDIT                   1183
#define IDC_FILEDATA_EDIT               1184
#define IDC_FILETIME_EDIT               1185
#define IDC_DECLINE_BUTTON              1187
#define IDC_DOWNLOAD_PROGRESS           1188
#define IDC_SAVEASPATH_EDIT             1189
#define IDC_STATUSDESCRUPTION_STATIC    1190
#define ID_BUTTON_OK                    1191
#define IDC_RECIPIENT_CCOOTREECTRL      1196
#define IDC_UPLOAD_PROGRESS             1197
#define IDC_RECIPIENTSNAME_EDIT         1198
#define IDC_CHECKBOX                    1199
#define IDC_BUTTON_MIN                  1200
#define IDC_BUTTON_BACK                 1201
#define IDC_BUTTON_MENU                 1201
#define IDC_INSERTSMILE_CHECK           1202
#define IDC_BUTTON_FORWARD              1202
#define IDC_BUTTON_SHOWOFFLINE          1202
#define IDC_RECEIVING_STATIC            1203
#define IDC_BUTTON_STOP                 1203
#define IDC_SENDING_STATIC              1204
#define IDC_MCINCOMING                  1204
#define IDC_BUTTON_REFRESH              1204
#define IDC_MCOUTGOING                  1205
#define IDC_BUTTON_MAX                  1205
#define IDC_MCDIALOG                    1206
#define IDC_BUTTON_RESTORE              1206
#define IDC_USER_STATIC                 1207
#define IDC_BUTTON_SAVEAS               1207
#define IDC_CCOOTREECTRL1               1208
#define IDC_CCOOTREECTRL                1208
#define IDC_USER_LIST                   1208
#define IDC_BRANDING                    1209
#define IDC_MCDIALOG2                   1209
#define IDC_MCFIND                      1209
#define IDC_FILENAME_STATIC             1211
#define IDC_ENTER_SEND_RADIO            1212
#define IDC_ENTER_NEWLINE_RADIO         1213
#define IDC_MCPROGRESSCTRL              1213
#define IDC_CTRLENTER_SEND_RADIO        1214
#define IDC_CTRLENTER_NEWLINE_RADIO     1215
#define IDC_ALTENTER_SEND_RADIO         1216
#define IDC_ALTENTER_NEWLINE_RADIO      1217
#define IDC_SHIFTENTER_SEND_RADIO       1218
#define IDC_SHIFTENTER_NEWLINE_RADIO    1219
#define IDC_ALTS_SEND_RADIO             1220
#define IDC_ALTS_NEWLINE_RADIO          1221
#define IDC_CTRLS_SEND_RADIO            1222
#define IDC_FILEDESCRIPTION2_EDIT       1222
#define IDC_CTRLS_NEWLINE_RADIO         1223
#define IDC_FILENAME2_STATIC            1223
#define IDC_MCMINI                      1224
#define IDC_MCBUTTONCTRL1               1224
#define IDC_BTN_X                       1224
#define IDC_BTN_CREATE                  1224
#define IDC_MCMAXIMINI                  1225
#define IDC_TITLE                       1225
#define IDC_BTN_COLOR                   1225
#define IDC_BTN_INVITE                  1225
#define IDC_BUTTON_YES                  1226
#define IDC_BTN_BOLD                    1226
#define IDC_BTN_UPDATE                  1226
#define IDC_BUTTON_NO                   1227
#define IDC_SOUNDPATH_LIST              1227
#define IDC_BTN_ITALIC                  1227
#define IDC_BTN_MINI                    1227
#define IDC_SELECT_BUTTON               1228
#define IDC_BTN_UNDERLINE               1228
#define IDC_BTN_LINE_RECEIVED           1228
#define IDC_MCUNDO                      1228
#define IDC_CLEAR_BUTTON                1229
#define IDC_MEDIAPLAYER1                1229
#define IDC_BTN_SMILES                  1229
#define IDC_BTN_LINE_SENT               1229
#define IDC_MCREDO                      1229
#define IDC_TEST_BUTTON                 1230
#define IDC_SHOCKWAVEFLASH1             1230
#define IDC_BTN_MIN                     1230
#define IDC_BTN_LINE_TOTAL              1230
#define IDC_MCCROP                      1230
#define IDC_ALERT_LIST                  1231
#define IDC_BTN_OPTIONS                 1231
#define IDC_MCZOOMOUT                   1231
#define IDC_APP_LIST                    1232
#define IDC_BTN_MENU                    1232
#define IDC_MCZOOMIN                    1232
#define IDC_DIRECTORY_TREE              1233
#define IDC_MCSCROLL                    1233
#define IDC_FILE_LIST                   1234
#define IDC_MCTEXT                      1234
#define IDC_VSPLITTER                   1235
#define IDC_MCPEN                       1235
#define IDC_MCPENCOLOR                  1236
#define IDC_MCBUTTONLIBRARY             1237
#define IDC_MCBUTTONTRANSFER            1238
#define IDC_CLEAR_CHATWINDOW_CHECK      1239
#define IDC_SHOWFRIENDSTATUS_CHECK      1240
#define IDC_RECEIVEDFILESPATH_EDIT      1241
#define IDC_INFOLINK_STATIC             1245
#define IDC_EXPLORER                    1246
#define IDC_APP_STATIC                  1246
#define IDC_STATUS_STATIC               1249
#define IDC_LOGO                        1250
#define IDC_APP_BAR                     1251
#define IDC_FRAME                       1252
#define IDC_BTN_APPLY                   1255
#define IDC_FRAME_EDIT                  1259
#define IDC_BTN_YES                     1266
#define IDC_BTN_NO                      1267
#define IDC_MESSAGE                     1276
#define IDC_HOTKEY1                     1281
#define IDC_TITLE_STATIC                1282
#define IDC_IN_EXPLORER                 1283
#define IDC_START_BUTTON                1285
#define IDC_ANIMATE                     1286
#define IDC_DOWNLOAD_STATIC             1287
#define IDC_START_STATIC                1288
#define IDC_EXPLORER1                   1288
#define IDC_EDIT_EXPLORER               1288
#define IDC_BUTTON1                     1289
#define IDC_BUTTON_ADD                  1289
#define IDC_LIST1                       1290
#define IDC_SERVER_LIST                 1290
#define IDC_USER_COLOR_LIST             1290
#define IDC_BUTTON_DEL                  1290
#define IDC_SMILE_LIST                  1290
#define IDC_REMOVE_IBN_FROM_TASK_BAR_CHECK 1291
#define IDC_INFO_COLOR_LIST             1291
#define IDC_BUTTON_EDIT                 1291
#define IDC_CCOCONFERENCECTRL           1292
#define IDC_EDIT_NAME                   1293
#define IDC_EDIT_DESCR                  1294
#define IDC_X                           1295
#define IDC_EDIT_INVITATION             1296
#define IDC_LOAD_LASTMES_EDIT           1300
#define IDC_LOAD_LASTMES_SPIN           1301
#define IDC_CCOOTREECTRL2               1303
#define IDC_CHECK_SHOWSENDTO            1304
#define IDC_COUNTTYPE_COMBO             1305
#define IDC_COST_EDIT                   1306
#define IDC_NETGRAPH_STATIC             1307
#define IDC_MESSAGE_SENT_STATIC         1308
#define IDC_MESSAGE_RECEIVED_STATIC     1309
#define IDC_FILE_SENT_STATIC            1310
#define IDC_FILE_RECEIVED_STATIC        1311
#define IDC_TOTAL_SENT_STATIC           1312
#define IDC_TOTAL_RECEIVED_STATIC       1313
#define IDC_TOTAL_COST_STATIC           1314
#define IDC_RADIO_IBN_ACTIONS           1314
#define IDC_RADIO_CONTACT_LIST          1315
#define IDC_RADIO_IBN_MICRO_BROWSER     1316
#define IDC_RADIO_STANDART_BROWSER      1317
#define IDC_CHECK_MICRO_HAS_MAXIMIZE    1318
#define IDC_MCSAVE                      1319
#define IDC_IMAGE_STATIC                1320
#define IDC_TIMEFILTERMODE_COMBO        1321
#define IDC_FROMTIME_DATETIMEPICKER     1322
#define IDC_TOTIME_DATETIMEPICKER       1323
#define IDC_BUTTON_SSL                  1324
#define IDC_MINIMIZE_ONCLOSE_CHECK      1324
#define IDC_BUTTON_LOGIN                1325
#define IDC_MESTEMPLATE_LIST            1325
#define IDC_NAME_STATIC                 1326
#define IDC_NAME_EDIT                   1327
#define IDC_NAME_STATIC2                1328
#define IDC_SEND_AUTOMATICALLY          1328
#define IDC_TEXT_EDIT                   1329
#define IDC_EDIT1                       1330
#define IDC_SMILEPREVIEW                1330
#define IDC_BTNFONT                     1331
#define IDC_GET_DEFAULT_BROWSER_FROM_REGISTRY 1340
#define IDC_CONTACTLIST_SORTBYFIRSTNAME 1341
#define IDC_UPDATE_AUTOCHECK            1342
#define IDS_INCOMING_MESSAGE_KEY        2233
#define IDS_INCOMING_FILE_KEY           2234
#define IDS_ONLINE_ALERT_KEY            2235
#define IDS_STARTUP_KEY                 2236
#define IDS_AUTHORIZATION_REQUEST_KEY   2238
#define IDS_NEW_ALERT_COME_KEY          2246
#define IDC_BUTTON_SEND                 10001
#define IDC_HISTORY                     10002
#define IDC_EDIT_MESSAGE                10003
#define IDC_FONT_COMBO                  10004
#define IDC_SIZE_COMBO                  10005
#define IDC_BOLD_CHECK                  10006
#define IDC_ITALIC_CHECK                10007
#define IDC_UNDERLINE_CHECK             10008
#define IDC_COLOR                       10009
#define IDC_BUTTON_ANSWER               10010
#define IDD_CANCEL_BUTTON               10011
#define IDC_NEXT_MES                    10012
#define IDB1                            15040
#define IDB22                           15041
#define IDB21                           15042
#define IDB33                           15043
#define IDB32                           15044
#define IDB31                           15045
#define IDB_DONTSHOWAGAIN               15046
#define IDB_OFS_START_EVENT             25000
#define IDB_HOME_BUTTON                 25001
#define IDB_PRODUCT_BUTTON              25002
#define IDB_DIR_BUTTON                  25003
#define IDB_DIALOG_BUTTON               25004
#define IDB_CUSTOMER_BUTTON             25005
#define IDB_OFS_END_EVENT               26000
#define ID_TRAY_MYSTATUS_ONLINE         32774
#define ID_TRAY_MYSTATUS_OFFLINE        32775
#define ID_TRAY_ABOUT                   32776
#define ID_TRAY_SHOWNEWMESSAGE          32777
#define ID_TREEMENU_SENDMESSAGE         32778
#define ID_TREEMENU_SENDFILE            32779
#define ID_STATUS_ONLINE                32780
#define ID_STATUS_INVISIBLE             32781
#define ID_STATUS_DND                   32782
#define ID_STATUS_AWAY                  32783
#define ID_STATUS_NA                    32784
#define ID_TREEMENU_DELETEUSER          32786
#define ID_TREEMENU_MESSAGESHISTORY     32788
#define ID_TREEMENU_USERDETAILS         32789
#define ID_TREEMENU_FLOATINGON          32790
#define ID_STATUS_OFFLINE               32791
#define ID_EDITMENU_PAST                32792
#define ID_EDITMENU_COPY                32793
#define ID_EDITMENU_CUT                 32794
#define ID_EDITMENU_DELETE              32795
#define ID_OPTIONS_SYNCHRONIZEHISTORY   32798
#define ID_TRAY_EXIT                    32799
#define ID_OPTIONS_PREFERENCES          32800
#define ID_TRAY_PREFERENCES             32801
#define ID_SENDFILE                     32803
#define ID_WEBCAM                       32804
#define ID_VOICE                        32805
#define ID_IGNORY                       32806
#define ID_ADDUSER                      32807
#define ID_FILE_SEND                    32808
#define ID_COLOR0                       32811
#define ID_FILE_PRINTASPLAINTEXT        32811
#define ID_COLOR1                       32812
#define ID_FILE_PREFERENCE              32812
#define ID_COLOR2                       32813
#define ID_COLOR3                       32814
#define ID_COLOR4                       32815
#define ID_COLOR5                       32816
#define ID_EDIT_PAST                    32816
#define ID_COLOR6                       32817
#define ID_EDIT_DELETE                  32817
#define ID_COLOR7                       32818
#define ID_EDIT_SELECTALL               32818
#define ID_COLOR8                       32819
#define ID_COLOR9                       32820
#define ID_VIEW_SHOWTIMESTAMPS          32820
#define ID_COLOR10                      32821
#define ID_VIEW_SHOWRECENTHISTORY       32821
#define ID_COLOR11                      32822
#define ID_VIEW_VIEWMESSAGEARHIVE       32822
#define ID_COLOR12                      32823
#define ID_FROMAT_IMVIROMENT            32823
#define ID_COLOR13                      32824
#define ID_FROMAT_FONT                  32824
#define ID_COLOR14                      32825
#define ID_FROMAT_SIZE                  32825
#define ID_COLOR15                      32826
#define ID_FROMAT_COLOR                 32826
#define ID_COLOR16                      32827
#define ID_FROMAT_BOLD                  32827
#define ID_FROMAT_ITALIC                32828
#define ID_FROMAT_UNDERLINE             32829
#define ID_FROMAT_COLOREFFECTS          32830
#define ID_FROMAT_DEFAULTFONTANDCOLOR   32831
#define ID_FROMAT_PLAYTYPINGSOUND       32832
#define ID_HELP_AUDIOSETUPWIZARD        32833
#define ID_HELP_MESSENGERHELP           32834
#define ID_HELP_HOWTOUSEMESSENGER       32835
#define ID_HELP_ABOUTMCMESSENGER        32836
#define IDF_BOLD                        32837
#define IDF_ITALIC                      32839
#define IDF_UNDERLINE                   32840
#define IDF_COLOR                       32841
#define IDF_SMILE                       32842
#define IDF_FONTNAME                    32843
#define IDF_FONTSIZE                    32844
#define ID_BUTTON32845                  32845
#define IDF_IMVIROMENT                  32846
#define ID_FORMAT_SIZE                  32847
#define ID_OPTIONS_ADDINIVITE_FINDUSERADDTOFRIENDS 32849
#define ID_OPTIONS_FILEMANAGER_DOWNLOAD 32850
#define ID_OPTIONS_FILEMANAGER_UPLOAD   32851
#define ID_OPTIONS_VIEWMYDETAILS        32853
#define ID_HISTORY_SYNHRONIZEHISTORY    32854
#define ID_HISTORY_PREFERENCES          32855
#define ID_TREEGROUP_SENDMESSAGE        32856
#define ID_TREEGROUP_SENDFILE           32857
#define ID_TREEMENU_SENDEMAIL           32858
#define ID_TREEGROUP_SENDEMAIL          32859
#define ID_FILESUPLOAD_UPLOAD           32860
#define ID_FILESUPLOAD_CLEARRECORD      32861
#define ID_FILESUPLOAD_CANCELTRANSFER   32862
#define ID_FILEDOWNLOAD_INFORMATION     32864
#define ID_FILEDOWNLOAD_CLEARRECORD     32865
#define ID_FILEDOWNLOAD_CANCELTRANSFORM 32866
#define ID_FILEDOWNLOAD_DOWNLOAD        32867
#define ID_FILEDOWNLOAD_MOVETOOFFLINE   32868
#define ID_FILEDOWNLOAD_OPEN            32869
#define ID_FILESUPLOAD_INFORMATION      32870
#define ID_FILEDOWNLOAD_GOTODIR         32871
#define ID_OPTIONS_LOGOFF               32872
#define ID_HISTORY_FIND                 32873
#define ID_CHATTREEMENU_SENDMESSAGE     32874
#define ID_CHATTREEMENU_ATTACH          32875
#define ID_CHATTREEMENU_VIEWDETAILS     32876
#define ID_CHATTREEMENU_EDITDETAILS     32877
#define ID_CHATTREEMENU_STATUS_INACTIVE 32878
#define ID_CHATTREEMENU_STATUS_ACTIVE   32879
#define ID_CHATTREEMENU_HISTORY         32881
#define ID_CHATTREEMENU_STATUS_LEAVE    32882
#define ID_CHATTREEMENU_ADDAFRIEND      32884
#define ID_OPTIONS_CONFERENCE_CREATENEW 32886
#define ID_WEBFOLDERS_VIEW_LARGEICONS   32888
#define ID_WEBFOLDERS_VIEW_SMALLICONS   32889
#define ID_WEBFOLDERS_VIEW_LIST         32890
#define ID_WEBFOLDERS_VIEW_DETAILS      32891
#define ID_WEBFOLDERS_REFRESH           32892
#define ID_WEBFOLDERS_GOTO_BACK         32894
#define ID_WEBFOLDERS_GOTO_FORWARD      32895
#define ID_TREEMENU_CONFERENCE_CREATENEW 32896
#define ID_TREEGROUP_CONFERENCE_CREATENEW 32897
#define ID_WEBFOLDERS_PASTE             32898
#define ID_WEBFOLDERSXP_VIEW_THUMBNAILS 32899
#define ID_WEBFOLDERSXP_VIEW_TILES      32900
#define ID_OPTIONS_NETWORKMONITOR       32902
#define ID_TREEMENU_ASSIGNTODO          32903
#define ID_TREEGROUP_ASSIGNTODO         32904
#define ID_RIGHTBUTTONDD_CANCEL         32905
#define ID_RIGHTBUTTONDD_ASSIGNTODO     32906
#define ID_RIGHTBUTTONDD_SENDFILE       32907
#define ID_RIGHTBUTTONDD_UPLOADFILE     32908
#define ID_RIGHTBUTTONDD_CREATEISSUE    32909
#define ID_TREEMENU_SENDSCREENSHOT      32911
#define ID_TREEMENU_SCREENCAPTURE_ASSINGTODO 32912
#define ID_TREEGROUP_SCREENCAPTURE_SEND 32913
#define ID_TREEGROUP_SCREENCAPTURE_ASSIGNTODO 32914
#define ID_TREEMENU_CREATEEVENT         32915
#define ID_TREEGROUP_CREATEEVENT        32916
#define ID_TOOLSMENU_MESSAGEHISTORY     32918
#define ID_TOOLSMENU_FILEMANAGE         32919
#define ID_TOOLSMENU_NETWORKMONITOR     32921
#define ID_TOOLSMENU_IBNTOOLBOX         32923
#define ID_TOOLSMENU_SCREENCAPTURE_SEND 32924
#define ID_TOOLSMENU_SCREENCAPTURE_ASSIGNTODO 32925
#define ID_TOOLSMENU_SCREENCAPTURE_CREATEISSUE 32926
#define ID_TRAY_REPORTABUG              32927
#define IDS_REGISTRY_KEY                57345
#define IDS_OFSMESSENGER_MAIN           61204
#define IDS_YOUOFFLINE                  61205
#define IDS_INVALID_LOGIN_OR_PASSWORD   61206
#define IDS_SHOWSENDTO                  61207

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        313
#define _APS_NEXT_COMMAND_VALUE         32930
#define _APS_NEXT_CONTROL_VALUE         1331
#define _APS_NEXT_SYMED_VALUE           175
#endif
#endif
