//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.IbnFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class McStateMachine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal McStateMachine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IbnFramework.McStateMachine", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current State.
        /// </summary>
        internal static string CurrentState {
            get {
                return ResourceManager.GetString("CurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Transition.
        /// </summary>
        internal static string CurrentTransition {
            get {
                return ResourceManager.GetString("CurrentTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Select Transition ].
        /// </summary>
        internal static string SelectTransition {
            get {
                return ResourceManager.GetString("SelectTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition.
        /// </summary>
        internal static string Transition {
            get {
                return ResourceManager.GetString("Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want use states and transitions select state machine..
        /// </summary>
        internal static string _mc_CommentCreate {
            get {
                return ResourceManager.GetString("_mc_CommentCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Machine.
        /// </summary>
        internal static string _mc_StateMachine {
            get {
                return ResourceManager.GetString("_mc_StateMachine", resourceCulture);
            }
        }
    }
}
