//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.IbnFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Admin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Admin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IbnFramework.Admin", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mode is &quot;Administration&quot;. You can see the advanced information..
        /// </summary>
        internal static string AdminMode {
            get {
                return ResourceManager.GetString("AdminMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Outgoing Messages.
        /// </summary>
        internal static string AllOutgoingMessages {
            get {
                return ResourceManager.GetString("AllOutgoingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit.
        /// </summary>
        internal static string Audit {
            get {
                return ResourceManager.GetString("Audit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed {0} Client Logins.
        /// </summary>
        internal static string AuditIbnClientLogin {
            get {
                return ResourceManager.GetString("AuditIbnClientLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Portal Logins.
        /// </summary>
        internal static string AuditWebLogin {
            get {
                return ResourceManager.GetString("AuditWebLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string ClientEmailMessage {
            get {
                return ResourceManager.GetString("ClientEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Default Profile ].
        /// </summary>
        internal static string DefaultProfile {
            get {
                return ResourceManager.GetString("DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered Messages.
        /// </summary>
        internal static string DeliveredMessages {
            get {
                return ResourceManager.GetString("DeliveredMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Attempts.
        /// </summary>
        internal static string DeliveryAttempts {
            get {
                return ResourceManager.GetString("DeliveryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current mode is &quot;Development&quot;. You can see only the necessary information..
        /// </summary>
        internal static string DevMode {
            get {
                return ResourceManager.GetString("DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit default value.
        /// </summary>
        internal static string EditDefValue {
            get {
                return ResourceManager.GetString("EditDefValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Messages.
        /// </summary>
        internal static string FailedMessages {
            get {
                return ResourceManager.GetString("FailedMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string FalseValue {
            get {
                return ResourceManager.GetString("FalseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Type.
        /// </summary>
        internal static string Field_ActType {
            get {
                return ResourceManager.GetString("Field_ActType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        internal static string Field_Attachment {
            get {
                return ResourceManager.GetString("Field_Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string Field_Client {
            get {
                return ResourceManager.GetString("Field_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Type.
        /// </summary>
        internal static string Field_CompType {
            get {
                return ResourceManager.GetString("Field_CompType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Field_Currency {
            get {
                return ResourceManager.GetString("Field_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverables.
        /// </summary>
        internal static string Field_Deliverables {
            get {
                return ResourceManager.GetString("Field_Deliverables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Assign Deadline.
        /// </summary>
        internal static string Field_ExpAssDead {
            get {
                return ResourceManager.GetString("Field_ExpAssDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Reply Deadline.
        /// </summary>
        internal static string Field_ExpRepDead {
            get {
                return ResourceManager.GetString("Field_ExpRepDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Resolution Deadline.
        /// </summary>
        internal static string Field_ExpResolDead {
            get {
                return ResourceManager.GetString("Field_ExpResolDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Categories.
        /// </summary>
        internal static string Field_GenCats {
            get {
                return ResourceManager.GetString("Field_GenCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        internal static string Field_Goals {
            get {
                return ResourceManager.GetString("Field_Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Categories.
        /// </summary>
        internal static string Field_IncCats {
            get {
                return ResourceManager.GetString("Field_IncCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be confirmed by Manager.
        /// </summary>
        internal static string Field_MustBeConfirm {
            get {
                return ResourceManager.GetString("Field_MustBeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Categories.
        /// </summary>
        internal static string Field_PrgCats {
            get {
                return ResourceManager.GetString("Field_PrgCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Field_Priority {
            get {
                return ResourceManager.GetString("Field_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope.
        /// </summary>
        internal static string Field_Scope {
            get {
                return ResourceManager.GetString("Field_Scope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Field_Severity {
            get {
                return ResourceManager.GetString("Field_Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Time.
        /// </summary>
        internal static string Field_TaskTime {
            get {
                return ResourceManager.GetString("Field_TaskTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Field_Type {
            get {
                return ResourceManager.GetString("Field_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Client field.
        /// </summary>
        internal static string generalAllowClient {
            get {
                return ResourceManager.GetString("generalAllowClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show General Categories field.
        /// </summary>
        internal static string generalAllowGeneralCategories {
            get {
                return ResourceManager.GetString("generalAllowGeneralCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Priority field.
        /// </summary>
        internal static string generalAllowPriority {
            get {
                return ResourceManager.GetString("generalAllowPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Task Time field.
        /// </summary>
        internal static string generalAllowTaskTime {
            get {
                return ResourceManager.GetString("generalAllowTaskTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Fields Visibility Settings.
        /// </summary>
        internal static string GeneralFieldsVisibility {
            get {
                return ResourceManager.GetString("GeneralFieldsVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can you check/uncheck the fields of portal objects in order to display them or not.&lt;br /&gt;
        ///		&lt;br /&gt;You can adjust dusplay of these fields for each of portal objects separately as well.&lt;br /&gt;
        ///		To do this follow the link..
        /// </summary>
        internal static string GeneralVisibilityWarning {
            get {
                return ResourceManager.GetString("GeneralVisibilityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change fields visibility for each object type.
        /// </summary>
        internal static string GoToObjectsSettings {
            get {
                return ResourceManager.GetString("GoToObjectsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibn Client Message.
        /// </summary>
        internal static string IbnClientMessage {
            get {
                return ResourceManager.GetString("IbnClientMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ibn Client Messages.
        /// </summary>
        internal static string IbnClientMessages {
            get {
                return ResourceManager.GetString("IbnClientMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Delivered.
        /// </summary>
        internal static string IsDelivered {
            get {
                return ResourceManager.GetString("IsDelivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Delivered Messages.
        /// </summary>
        internal static string NotDeliveredMessages {
            get {
                return ResourceManager.GetString("NotDeliveredMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Type Fields Visibility Settings.
        /// </summary>
        internal static string ObjectFieldsVisibility {
            get {
                return ResourceManager.GetString("ObjectFieldsVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Type.
        /// </summary>
        internal static string ObjectType {
            get {
                return ResourceManager.GetString("ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Entry.
        /// </summary>
        internal static string ObjectType_CalendarEntry {
            get {
                return ResourceManager.GetString("ObjectType_CalendarEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string ObjectType_Document {
            get {
                return ResourceManager.GetString("ObjectType_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string ObjectType_Incident {
            get {
                return ResourceManager.GetString("ObjectType_Incident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string ObjectType_Project {
            get {
                return ResourceManager.GetString("ObjectType_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string ObjectType_Task {
            get {
                return ResourceManager.GetString("ObjectType_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToDo.
        /// </summary>
        internal static string ObjectType_ToDo {
            get {
                return ResourceManager.GetString("ObjectType_ToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can you check/uncheck the several fields for every object type in order to display them or not..
        /// </summary>
        internal static string ObjectVisibilityWarning {
            get {
                return ResourceManager.GetString("ObjectVisibilityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode of Operation.
        /// </summary>
        internal static string OperationMode {
            get {
                return ResourceManager.GetString("OperationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing Message Queue.
        /// </summary>
        internal static string OutgoingMessageQueue {
            get {
                return ResourceManager.GetString("OutgoingMessageQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outgoing Message Queues.
        /// </summary>
        internal static string OutgoingMessageQueues {
            get {
                return ResourceManager.GetString("OutgoingMessageQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permitted.
        /// </summary>
        internal static string PermittedShe {
            get {
                return ResourceManager.GetString("PermittedShe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project View.
        /// </summary>
        internal static string ProjectView {
            get {
                return ResourceManager.GetString("ProjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project view mode: Left Menu..
        /// </summary>
        internal static string ProjectWithLeftMenu {
            get {
                return ResourceManager.GetString("ProjectWithLeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current project view mode: Top Tabs..
        /// </summary>
        internal static string ProjectWithTabs {
            get {
                return ResourceManager.GetString("ProjectWithTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Rss for meta objects is enabled..
        /// </summary>
        internal static string RssDisableDescription {
            get {
                return ResourceManager.GetString("RssDisableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off Rss for meta objects.
        /// </summary>
        internal static string RssDisableText {
            get {
                return ResourceManager.GetString("RssDisableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Rss for meta objects is disabled..
        /// </summary>
        internal static string RssEnableDescription {
            get {
                return ResourceManager.GetString("RssEnableDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on Rss for meta objects.
        /// </summary>
        internal static string RssEnableText {
            get {
                return ResourceManager.GetString("RssEnableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rss Settings.
        /// </summary>
        internal static string RssHeader {
            get {
                return ResourceManager.GetString("RssHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All the settings have been successfully saved!.
        /// </summary>
        internal static string SaveSuccessfull {
            get {
                return ResourceManager.GetString("SaveSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were saved successfully.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to &quot;Administration&quot; mode..
        /// </summary>
        internal static string SwitchToAdminMode {
            get {
                return ResourceManager.GetString("SwitchToAdminMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to &quot;Development&quot; mode..
        /// </summary>
        internal static string SwitchToDevMode {
            get {
                return ResourceManager.GetString("SwitchToDevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to &quot;Left Menu&quot; mode..
        /// </summary>
        internal static string SwitchToProjectWithLeftMenu {
            get {
                return ResourceManager.GetString("SwitchToProjectWithLeftMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to &quot;Top Tabs&quot; mode..
        /// </summary>
        internal static string SwitchToProjectWithTabs {
            get {
                return ResourceManager.GetString("SwitchToProjectWithTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Value.
        /// </summary>
        internal static string tDefaultValue {
            get {
                return ResourceManager.GetString("tDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create/Edit.
        /// </summary>
        internal static string tEdit {
            get {
                return ResourceManager.GetString("tEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string tField {
            get {
                return ResourceManager.GetString("tField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        internal static string tObjectNotSet {
            get {
                return ResourceManager.GetString("tObjectNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string TrueValue {
            get {
                return ResourceManager.GetString("TrueValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string tView {
            get {
                return ResourceManager.GetString("tView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpermitted.
        /// </summary>
        internal static string UnpermittedShe {
            get {
                return ResourceManager.GetString("UnpermittedShe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string webDavSessionDelete {
            get {
                return ResourceManager.GetString("webDavSessionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string webDavSessionDuration {
            get {
                return ResourceManager.GetString("webDavSessionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        internal static string webDavSessionFileName {
            get {
                return ResourceManager.GetString("webDavSessionFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active edit sessions.
        /// </summary>
        internal static string webDavSessionList {
            get {
                return ResourceManager.GetString("webDavSessionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked By.
        /// </summary>
        internal static string webDavSessionLockBy {
            get {
                return ResourceManager.GetString("webDavSessionLockBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active sessions.
        /// </summary>
        internal static string webDavSessionNoData {
            get {
                return ResourceManager.GetString("webDavSessionNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string webDavSessionStartTime {
            get {
                return ResourceManager.GetString("webDavSessionStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Personalization.
        /// </summary>
        internal static string WorkspacePersonalization {
            get {
                return ResourceManager.GetString("WorkspacePersonalization", resourceCulture);
            }
        }
    }
}
