//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.IbnFramework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Incident {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Incident() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.IbnFramework.Incident", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Inactive.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened Issues.
        /// </summary>
        internal static string ActiveIssues {
            get {
                return ResourceManager.GetString("ActiveIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Finish Date.
        /// </summary>
        internal static string ActualFinishDate {
            get {
                return ResourceManager.GetString("ActualFinishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Open Date.
        /// </summary>
        internal static string ActualOpenDate {
            get {
                return ResourceManager.GetString("ActualOpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Related Issue From Clipboard.
        /// </summary>
        internal static string AddRelFromClip {
            get {
                return ResourceManager.GetString("AddRelFromClip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All articles.
        /// </summary>
        internal static string AllArticles {
            get {
                return ResourceManager.GetString("AllArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Denied.
        /// </summary>
        internal static string AllDenied {
            get {
                return ResourceManager.GetString("AllDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Issues.
        /// </summary>
        internal static string AllIssues {
            get {
                return ResourceManager.GetString("AllIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Issues Export.
        /// </summary>
        internal static string AllIssuesExport {
            get {
                return ResourceManager.GetString("AllIssuesExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Posts.
        /// </summary>
        internal static string AllPostsPrintForum {
            get {
                return ResourceManager.GetString("AllPostsPrintForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string AllSet {
            get {
                return ResourceManager.GetString("AllSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any.
        /// </summary>
        internal static string AllSetMale {
            get {
                return ResourceManager.GetString("AllSetMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge Base.
        /// </summary>
        internal static string ArticlesList {
            get {
                return ResourceManager.GetString("ArticlesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Responsible.
        /// </summary>
        internal static string ChangeResponsible {
            get {
                return ResourceManager.GetString("ChangeResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Issues.
        /// </summary>
        internal static string ClosedIssues {
            get {
                return ResourceManager.GetString("ClosedIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseIssue {
            get {
                return ResourceManager.GetString("CloseIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        internal static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-created issues.
        /// </summary>
        internal static string CreatorSet {
            get {
                return ResourceManager.GetString("CreatorSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Current User].
        /// </summary>
        internal static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Issue.
        /// </summary>
        internal static string DeleteIssue {
            get {
                return ResourceManager.GetString("DeleteIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteIssue2 {
            get {
                return ResourceManager.GetString("DeleteIssue2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this issue?.
        /// </summary>
        internal static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Down.
        /// </summary>
        internal static string DownPriority {
            get {
                return ResourceManager.GetString("DownPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to turn down priority for all selected issues?.
        /// </summary>
        internal static string DownPriorityWarning {
            get {
                return ResourceManager.GetString("DownPriorityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Issue.
        /// </summary>
        internal static string EditIssue {
            get {
                return ResourceManager.GetString("EditIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Resolve Date.
        /// </summary>
        internal static string ExpectedResolveDate {
            get {
                return ResourceManager.GetString("ExpectedResolveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Response Date.
        /// </summary>
        internal static string ExpectedResponseDate {
            get {
                return ResourceManager.GetString("ExpectedResponseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues Export.
        /// </summary>
        internal static string ExportIssues {
            get {
                return ResourceManager.GetString("ExportIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        internal static string FieldsTab {
            get {
                return ResourceManager.GetString("FieldsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string FiltersTab {
            get {
                return ResourceManager.GetString("FiltersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum Information.
        /// </summary>
        internal static string ForumInfoPrinting {
            get {
                return ResourceManager.GetString("ForumInfoPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Category.
        /// </summary>
        internal static string GenCat {
            get {
                return ResourceManager.GetString("GenCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Info.
        /// </summary>
        internal static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralTab {
            get {
                return ResourceManager.GetString("GeneralTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By.
        /// </summary>
        internal static string GroupBy {
            get {
                return ResourceManager.GetString("GroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Contacts.
        /// </summary>
        internal static string GroupByContacts {
            get {
                return ResourceManager.GetString("GroupByContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Contacts.
        /// </summary>
        internal static string GroupByContactSet {
            get {
                return ResourceManager.GetString("GroupByContactSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Issue Boxes.
        /// </summary>
        internal static string GroupByIssBoxes {
            get {
                return ResourceManager.GetString("GroupByIssBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Issue Boxes.
        /// </summary>
        internal static string GroupByIssBoxSet {
            get {
                return ResourceManager.GetString("GroupByIssBoxSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Projects.
        /// </summary>
        internal static string GroupByPrj {
            get {
                return ResourceManager.GetString("GroupByPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Projects.
        /// </summary>
        internal static string GroupByPrjSet {
            get {
                return ResourceManager.GetString("GroupByPrjSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Responsibles.
        /// </summary>
        internal static string GroupByResp {
            get {
                return ResourceManager.GetString("GroupByResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By Responsibles.
        /// </summary>
        internal static string GroupByRespSet {
            get {
                return ResourceManager.GetString("GroupByRespSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string GroupContacts {
            get {
                return ResourceManager.GetString("GroupContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Boxes.
        /// </summary>
        internal static string GroupIssBox {
            get {
                return ResourceManager.GetString("GroupIssBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No Project].
        /// </summary>
        internal static string GroupNoPrj {
            get {
                return ResourceManager.GetString("GroupNoPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string GroupPrj {
            get {
                return ResourceManager.GetString("GroupPrj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Responsibility.
        /// </summary>
        internal static string GroupResp {
            get {
                return ResourceManager.GetString("GroupResp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string GroupRespTitle {
            get {
                return ResourceManager.GetString("GroupRespTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        internal static string GroupsTab {
            get {
                return ResourceManager.GetString("GroupsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Old View.
        /// </summary>
        internal static string HideOldView {
            get {
                return ResourceManager.GetString("HideOldView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to hide old view?.
        /// </summary>
        internal static string HideOldViewWarning {
            get {
                return ResourceManager.GetString("HideOldViewWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import/Export.
        /// </summary>
        internal static string ImportExport {
            get {
                return ResourceManager.GetString("ImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Issues.
        /// </summary>
        internal static string ImportIssues {
            get {
                return ResourceManager.GetString("ImportIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues &amp; Incidents.
        /// </summary>
        internal static string IncidentList {
            get {
                return ResourceManager.GetString("IncidentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this view for all users.
        /// </summary>
        internal static string IsPublicView {
            get {
                return ResourceManager.GetString("IsPublicView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Category.
        /// </summary>
        internal static string IssCat {
            get {
                return ResourceManager.GetString("IssCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string IssClient {
            get {
                return ResourceManager.GetString("IssClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue #.
        /// </summary>
        internal static string IssCode {
            get {
                return ResourceManager.GetString("IssCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Forum Post View.
        /// </summary>
        internal static string IssForumPost {
            get {
                return ResourceManager.GetString("IssForumPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID #.
        /// </summary>
        internal static string IssId {
            get {
                return ResourceManager.GetString("IssId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Box.
        /// </summary>
        internal static string IssIssBox {
            get {
                return ResourceManager.GetString("IssIssBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string IssResponsible {
            get {
                return ResourceManager.GetString("IssResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string IssStatus {
            get {
                return ResourceManager.GetString("IssStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string IssTitle {
            get {
                return ResourceManager.GetString("IssTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check fields to print Issue Information.
        /// </summary>
        internal static string IssueGenInfoPrinting {
            get {
                return ResourceManager.GetString("IssueGenInfoPrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Resources.
        /// </summary>
        internal static string IssueRes {
            get {
                return ResourceManager.GetString("IssueRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IssueViewCreation {
            get {
                return ResourceManager.GetString("IssueViewCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create new issue view.
        /// </summary>
        internal static string IssueViewCreationSubHeader {
            get {
                return ResourceManager.GetString("IssueViewCreationSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue View Management.
        /// </summary>
        internal static string IssueViewCreationTitle {
            get {
                return ResourceManager.GetString("IssueViewCreationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue View Report.
        /// </summary>
        internal static string IssueViewReport {
            get {
                return ResourceManager.GetString("IssueViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        internal static string IssUpdated {
            get {
                return ResourceManager.GetString("IssUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 Posts.
        /// </summary>
        internal static string Last3PostsPrintForum {
            get {
                return ResourceManager.GetString("Last3PostsPrintForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        internal static string LastPostPrintForum {
            get {
                return ResourceManager.GetString("LastPostPrintForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relate issues.
        /// </summary>
        internal static string MakeRelation {
            get {
                return ResourceManager.GetString("MakeRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed issues.
        /// </summary>
        internal static string ManagerSet {
            get {
                return ResourceManager.GetString("ManagerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark As Spam.
        /// </summary>
        internal static string MarkAsSpam {
            get {
                return ResourceManager.GetString("MarkAsSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These issues are marked as Spam.&lt;br/&gt;
        ///	Select the next action to do..
        /// </summary>
        internal static string MarkAsSpamText {
            get {
                return ResourceManager.GetString("MarkAsSpamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Article.
        /// </summary>
        internal static string NewArticle {
            get {
                return ResourceManager.GetString("NewArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Issue.
        /// </summary>
        internal static string NewIssue {
            get {
                return ResourceManager.GetString("NewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New View.
        /// </summary>
        internal static string NewIssueView {
            get {
                return ResourceManager.GetString("NewIssueView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Message.
        /// </summary>
        internal static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create any new issue view with your own fieldset. Please, select a fieldset from the dropdown and proceed to the next step..
        /// </summary>
        internal static string NewViewStep1Comment {
            get {
                return ResourceManager.GetString("NewViewStep1Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create any new issue view with your own grouping setting. Please, select a grouping field from the dropdown and proceed to the next step..
        /// </summary>
        internal static string NewViewStep2Comment {
            get {
                return ResourceManager.GetString("NewViewStep2Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is ready to create a new view for issues list. Please, type view name..
        /// </summary>
        internal static string NewViewStep4Comment {
            get {
                return ResourceManager.GetString("NewViewStep4Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create any new issue view with your own fieldset. Please, select a fieldset from the dropdown..
        /// </summary>
        internal static string NewViewTab1Comment {
            get {
                return ResourceManager.GetString("NewViewTab1Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create any new issue view with your own grouping setting. Please, select a grouping field from the dropdown..
        /// </summary>
        internal static string NewViewTab2Comment {
            get {
                return ResourceManager.GetString("NewViewTab2Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything is ready to create a new view for issues list. Please, type view name..
        /// </summary>
        internal static string NewViewTab4Comment {
            get {
                return ResourceManager.GetString("NewViewTab4Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Post.
        /// </summary>
        internal static string NextPost {
            get {
                return ResourceManager.GetString("NextPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Grouping.
        /// </summary>
        internal static string NoGroupBy {
            get {
                return ResourceManager.GetString("NoGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no issues selected for status changing!.
        /// </summary>
        internal static string NoItemsSelected {
            get {
                return ResourceManager.GetString("NoItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no issues selected for responsible changing!.
        /// </summary>
        internal static string NoItemsSelectedForResponsible {
            get {
                return ResourceManager.GetString("NoItemsSelectedForResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Print.
        /// </summary>
        internal static string NotPrintForum {
            get {
                return ResourceManager.GetString("NotPrintForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Check.
        /// </summary>
        internal static string OnCheck {
            get {
                return ResourceManager.GetString("OnCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only overdue.
        /// </summary>
        internal static string OnlyOverdue {
            get {
                return ResourceManager.GetString("OnlyOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only unanswered.
        /// </summary>
        internal static string OnlyUnanswered {
            get {
                return ResourceManager.GetString("OnlyUnanswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Assigned.
        /// </summary>
        internal static string OutOfPersonalResponsibility {
            get {
                return ResourceManager.GetString("OutOfPersonalResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Assigned.
        /// </summary>
        internal static string OutOfPersonalResponsibilityFilter {
            get {
                return ResourceManager.GetString("OutOfPersonalResponsibilityFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        internal static string Overdue {
            get {
                return ResourceManager.GetString("Overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Messages.
        /// </summary>
        internal static string PendingMessages {
            get {
                return ResourceManager.GetString("PendingMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Post.
        /// </summary>
        internal static string PrevPost {
            get {
                return ResourceManager.GetString("PrevPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Settings.
        /// </summary>
        internal static string PrintPreviewSettings {
            get {
                return ResourceManager.GetString("PrintPreviewSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Forum Post View.
        /// </summary>
        internal static string QLastForumPost {
            get {
                return ResourceManager.GetString("QLastForumPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Tracking.
        /// </summary>
        internal static string QTrackIssue {
            get {
                return ResourceManager.GetString("QTrackIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Tracking.
        /// </summary>
        internal static string QuickTracking {
            get {
                return ResourceManager.GetString("QuickTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ All Denied ].
        /// </summary>
        internal static string RespAllDenied {
            get {
                return ResourceManager.GetString("RespAllDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Group Responsibility ].
        /// </summary>
        internal static string RespGroup {
            get {
                return ResourceManager.GetString("RespGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ Not Set ].
        /// </summary>
        internal static string RespNotSet {
            get {
                return ResourceManager.GetString("RespNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        internal static string ResponsibleNotAssigned {
            get {
                return ResourceManager.GetString("ResponsibleNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible can not be changed for the following Issues:&lt;br /&gt;{0}.
        /// </summary>
        internal static string ResponsibleNotChanged {
            get {
                return ResourceManager.GetString("ResponsibleNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsibled issues.
        /// </summary>
        internal static string ResponsibleSet {
            get {
                return ResourceManager.GetString("ResponsibleSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Field Set.
        /// </summary>
        internal static string SelectFieldSet {
            get {
                return ResourceManager.GetString("SelectFieldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Grouping Field.
        /// </summary>
        internal static string SelectGroupingField {
            get {
                return ResourceManager.GetString("SelectGroupingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Responsible.
        /// </summary>
        internal static string SelectRes {
            get {
                return ResourceManager.GetString("SelectRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Issue View Title.
        /// </summary>
        internal static string SelectTitle {
            get {
                return ResourceManager.GetString("SelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string Severity {
            get {
                return ResourceManager.GetString("Severity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        internal static string showClient {
            get {
                return ResourceManager.GetString("showClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Code.
        /// </summary>
        internal static string showCode {
            get {
                return ResourceManager.GetString("showCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Info.
        /// </summary>
        internal static string showCreationInfo {
            get {
                return ResourceManager.GetString("showCreationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string showDescription {
            get {
                return ResourceManager.GetString("showDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Response Date.
        /// </summary>
        internal static string showExpectedDate {
            get {
                return ResourceManager.GetString("showExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General categories.
        /// </summary>
        internal static string showGenCats {
            get {
                return ResourceManager.GetString("showGenCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Box Title.
        /// </summary>
        internal static string showIssBox {
            get {
                return ResourceManager.GetString("showIssBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue categories.
        /// </summary>
        internal static string showIssCats {
            get {
                return ResourceManager.GetString("showIssCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        internal static string showLastModifiedInfo {
            get {
                return ResourceManager.GetString("showLastModifiedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        internal static string showManager {
            get {
                return ResourceManager.GetString("showManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Date.
        /// </summary>
        internal static string showOpenDate {
            get {
                return ResourceManager.GetString("showOpenDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string showPriority {
            get {
                return ResourceManager.GetString("showPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected Resolved Date.
        /// </summary>
        internal static string showResolveDate {
            get {
                return ResourceManager.GetString("showResolveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string showResponsible {
            get {
                return ResourceManager.GetString("showResponsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string showStatus {
            get {
                return ResourceManager.GetString("showStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string showTitle {
            get {
                return ResourceManager.GetString("showTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string StandardFieldSet {
            get {
                return ResourceManager.GetString("StandardFieldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status can not be changed to &lt;b&gt;{0}&lt;/b&gt; for the following Issues:&lt;br /&gt;{1}.
        /// </summary>
        internal static string StatusNotChanged {
            get {
                return ResourceManager.GetString("StatusNotChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old View Turn On.
        /// </summary>
        internal static string SwitchTitle {
            get {
                return ResourceManager.GetString("SwitchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old View Turn On.
        /// </summary>
        internal static string SwithToOldView {
            get {
                return ResourceManager.GetString("SwithToOldView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Views.
        /// </summary>
        internal static string SystemViews {
            get {
                return ResourceManager.GetString("SystemViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Existing Issue.
        /// </summary>
        internal static string tAddToExist {
            get {
                return ResourceManager.GetString("tAddToExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Cloud.
        /// </summary>
        internal static string TagCloud {
            get {
                return ResourceManager.GetString("TagCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Checked.
        /// </summary>
        internal static string tApproveChecked {
            get {
                return ResourceManager.GetString("tApproveChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to approve all checked messages?.
        /// </summary>
        internal static string tApproveCheckedWarning {
            get {
                return ResourceManager.GetString("tApproveCheckedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to approve this message?.
        /// </summary>
        internal static string tApproveWarning {
            get {
                return ResourceManager.GetString("tApproveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this article?.
        /// </summary>
        internal static string tDeleteArticleWarning {
            get {
                return ResourceManager.GetString("tDeleteArticleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Checked.
        /// </summary>
        internal static string tDeleteChecked {
            get {
                return ResourceManager.GetString("tDeleteChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete all checked messages?.
        /// </summary>
        internal static string tDeleteCheckedWarning {
            get {
                return ResourceManager.GetString("tDeleteCheckedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this message?.
        /// </summary>
        internal static string tDeleteWarning {
            get {
                return ResourceManager.GetString("tDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Recipients.
        /// </summary>
        internal static string tExternalRecipients {
            get {
                return ResourceManager.GetString("tExternalRecipients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        internal static string TimelineFieldSet {
            get {
                return ResourceManager.GetString("TimelineFieldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Box.
        /// </summary>
        internal static string tIncBox {
            get {
                return ResourceManager.GetString("tIncBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Is Required!.
        /// </summary>
        internal static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No Subject].
        /// </summary>
        internal static string tNosubject {
            get {
                return ResourceManager.GetString("tNosubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string tPendCreated {
            get {
                return ResourceManager.GetString("tPendCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string tPendFrom {
            get {
                return ResourceManager.GetString("tPendFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string tPendId {
            get {
                return ResourceManager.GetString("tPendId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string tPendSubj {
            get {
                return ResourceManager.GetString("tPendSubj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string tPendTo {
            get {
                return ResourceManager.GetString("tPendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking.
        /// </summary>
        internal static string TrackingFieldSet {
            get {
                return ResourceManager.GetString("TrackingFieldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Responsibility.
        /// </summary>
        internal static string tRespGroup {
            get {
                return ResourceManager.GetString("tRespGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        internal static string tRespNotSet {
            get {
                return ResourceManager.GetString("tRespNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose diagram type.
        /// </summary>
        internal static string tSelectDiagram {
            get {
                return ResourceManager.GetString("tSelectDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Issue.
        /// </summary>
        internal static string tSelectIncident {
            get {
                return ResourceManager.GetString("tSelectIncident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On.
        /// </summary>
        internal static string TurnOn {
            get {
                return ResourceManager.GetString("TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unassigned Issues.
        /// </summary>
        internal static string UnassignedIssues {
            get {
                return ResourceManager.GetString("UnassignedIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Up.
        /// </summary>
        internal static string UpPriority {
            get {
                return ResourceManager.GetString("UpPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to turn up priority for all selected issues?.
        /// </summary>
        internal static string UpPriorityWarning {
            get {
                return ResourceManager.GetString("UpPriorityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Views.
        /// </summary>
        internal static string UserViews {
            get {
                return ResourceManager.GetString("UserViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewFieldSet {
            get {
                return ResourceManager.GetString("ViewFieldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Issue.
        /// </summary>
        internal static string ViewIssue {
            get {
                return ResourceManager.GetString("ViewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Issues Export.
        /// </summary>
        internal static string ViewIssuesExport {
            get {
                return ResourceManager.GetString("ViewIssuesExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Page Issues Export.
        /// </summary>
        internal static string VisibleIssuesExport {
            get {
                return ResourceManager.GetString("VisibleIssuesExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some issues have not been changed because of no access allowed!.
        /// </summary>
        internal static string WereErrors {
            get {
                return ResourceManager.GetString("WereErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows general  information regarding issues.
        /// </summary>
        internal static string _mc_ChartReportDescription {
            get {
                return ResourceManager.GetString("_mc_ChartReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select grouping field.
        /// </summary>
        internal static string _mc_ChartReportPP {
            get {
                return ResourceManager.GetString("_mc_ChartReportPP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue&amp;nbsp;chart.
        /// </summary>
        internal static string _mc_ChartReportTitle {
            get {
                return ResourceManager.GetString("_mc_ChartReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Custom].
        /// </summary>
        internal static string _mc_CustomFilterSet {
            get {
                return ResourceManager.GetString("_mc_CustomFilterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete FilterSet.
        /// </summary>
        internal static string _mc_DeleteFilterSet {
            get {
                return ResourceManager.GetString("_mc_DeleteFilterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this filterset?.
        /// </summary>
        internal static string _mc_DeleteFilterSetWarning {
            get {
                return ResourceManager.GetString("_mc_DeleteFilterSetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete View.
        /// </summary>
        internal static string _mc_DeleteView {
            get {
                return ResourceManager.GetString("_mc_DeleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this view?.
        /// </summary>
        internal static string _mc_DeleteViewWarning {
            get {
                return ResourceManager.GetString("_mc_DeleteViewWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Filter.
        /// </summary>
        internal static string _mc_EditFilter {
            get {
                return ResourceManager.GetString("_mc_EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string _mc_FilterSet {
            get {
                return ResourceManager.GetString("_mc_FilterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilterSet Name.
        /// </summary>
        internal static string _mc_FilterSetName {
            get {
                return ResourceManager.GetString("_mc_FilterSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by.
        /// </summary>
        internal static string _mc_GroupType {
            get {
                return ResourceManager.GetString("_mc_GroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Desk workspace.
        /// </summary>
        internal static string _mc_HdmWs {
            get {
                return ResourceManager.GetString("_mc_HdmWs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Role.
        /// </summary>
        internal static string _mc_MyRole {
            get {
                return ResourceManager.GetString("_mc_MyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Filter.
        /// </summary>
        internal static string _mc_ResetFilter {
            get {
                return ResourceManager.GetString("_mc_ResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Name.
        /// </summary>
        internal static string _mc_SetName {
            get {
                return ResourceManager.GetString("_mc_SetName", resourceCulture);
            }
        }
    }
}
